### ISSUE TITLE
Uac not working in non integrated apps

### ISSUE THREAD

**Issue by Theoldnation** [AveYo/MediaCreationTool.bat#100]
it is what i said, uac will not get prompted when trying tu run as administrator any non integrated with the system applications

**Comment by AveYo** [comment]
Please reopen / comment if you have further input and why you think it's the script at fault (it should auto-elevate itself when needed)

**Comment by AveYo** [comment]
@Theoldnation might want to try the updated script, I believe it will fix your issue (probably some weird path)

**Comment by Theoldnation** [comment]
I had discovered that was not a problem with your script at all, i had read the latest changelog from the new insider build which it is on beta and preview channel and specifies, that they solved an issue where UAC wasn't prompting at all after some installs
