### ISSUE TITLE
when I try to install "A media driver your computer needs is missing. This could be a DVD, USB or Hard Disk driver..." 

### ISSUE THREAD

**Issue by massimoap** [AveYo/MediaCreationTool.bat#102]
Clean install. halts on the message A media driver your computer needs is missing. This could be a DVD, USB or Hard Disk driver..."

**Comment by AveYo** [comment]
Ask for support on your device manufacturer website.  
You probably need a driver (called "F6" mass storage driver) for USB3/RST.  
[For example](https://www.dell.com/community/Inspiron-Desktops/Windows-USB-Clean-Install-A-media-driver-your-computer-needs-is/td-p/7320485)

You could also try a USB2 port on your device (if you have any).

**Comment by dotMorten** [comment]
I hit this too when using this tool. If I don't use this tool and just let it create the standard Win11 iso that doesn't happen, but I'm using this to create an Enterprise version.

**Comment by dotMorten** [comment]
I think I know the issue: I took the USB key out after the media creation tool closed, thinking it was done. However the script was still running for quite a while after the fact. Make sure you wait till the commandline tool exists (it'll look like it's stuck on "Started UsbLayout" for a long time.

**Comment by AveYo** [comment]
@dotMorten haHa, thanks! 
Guess it's easier to miss something still runs if using combined taskbar buttons..  
Might be a good idea for next update to add a notice not to remove the USB stick until finished.

**Comment by dotMorten** [comment]
yeah the user experience could probably be improved a little there.
FYI just confirming it installed fine now that I let it finish.

**Comment by AveYo** [comment]
I have finally addressed the USBLayout stage not showing any progress.
Setup UI now hides near the end, then script gives it's own USB progress, in MB - ain't that neat?
Thank you!
