### ISSUE TITLE
I'm havin' a bad time gettin' TPM 2.0 failed checks despite attempting Auto-Upgrade & Auto-ISO

### ISSUE THREAD

**Issue by Jaladhjin** [AveYo/MediaCreationTool.bat#107]
I'm not entirely sure what to do.

I'm currently on Windows 10 Pro 21H2 attempting to upgrade.

Auto Upgrade got me to a point where I'm Downloading Windows 11 but it has been @ 0% for like 10 minutes now.

I was able to download the ISO so I feel confident the download itself isn't getting blocked not sure what's going on.

I'm not very smart so it's entirely possible I'm not doing this correctly.

As long as I don't use MCT Defaults all other options should be patching TPM checks & what not correct?

It doesn't seem to be for me.

**Comment by AveYo** [comment]
If you have the ISO downloaded,  
mount it (double-click) and note the new drive letter (**J:** or something, used below),
then open a powershell window and enter:

start '**J:**\sources\setupprep.exe' '/SelfHost /Product Server /Auto Upgrade /MigChoice Upgrade /Compat IgnoreWarning /MigrateDrivers All /ResizeRecoveryPartition Disable /ShowOOBE None /Telemetry Disable /CompactOS Disable /DynamicUpdate Enable'

If you have iso made by the script, then mount it and double-click `auto.cmd` script, not setup.exe  
it is mentioned in the readme that upgrade is bypassed via `auto.cmd`.
