### ISSUE TITLE
Bypass cpu work but secure boot wont work

### ISSUE THREAD

**Issue by william-mask** [AveYo/MediaCreationTool.bat#11]
After run No_11_setup_Checks_v2, i was able to bypass the cpu check but not the secure boot (attached photos), how to resolve this?

![1](https://user-images.githubusercontent.com/93060959/138574947-da42efab-963e-4c14-8992-f440c5dc96f2.jpg)

![2](https://user-images.githubusercontent.com/93060959/138574954-718723ee-f75b-4876-8376-ec213e1ef41a.jpg)

**Comment by Dromandus** [comment]
I have the same situation. :(

**Comment by DIDIERBZH78** [comment]
After completing all the process and started the installation I have the same situation with error on the processor type that is not recognised... So your patch is not working as planed...
<img width="520" alt="Win 11 install Capture" src="https://user-images.githubusercontent.com/39096423/140840492-eface84d-c584-4bd3-aa2e-d931d32c2509.PNG">

**Comment by AveYo** [comment]
the bypass is not enabled by default in the last version, 
**you need to use `auto.cmd` to start the upgrade, not `setup.exe`**  
then the setup would have shown _Windows Server_ label

next update will switch back to my original method that works for `setup.exe` with or without Dynamic Update checked

**Comment by AveYo** [comment]
updated

**Comment by Dromandus** [comment]
Thanks a lot :) 
Regards
