### ISSUE TITLE
Installs Windows 11 Server, despite the selection of Consumer Windows 11

### ISSUE THREAD

**Issue by JaydenDev** [AveYo/MediaCreationTool.bat#110]
I use the utility to bypass requirements for Windows 11 installation, for an in-place install. However, during the second to last stage of the installation, I had a window popup saying "Windows 11 server". For the last portion, It says "Installing Windows Server". Which, I want Windows 11 Professional. I prefer this utility over standard methods of installation, I hope it gets fixed soon!

**Comment by AveYo** [comment]
That's what you actually get, Windows 11 Professional.  
The 'Windows Server' is just a label, a side-effect of the bypass used.

**Comment by JaydenDev** [comment]
> That's what you actually get, Windows 11 Professional. The 'Windows Server' is just a label, a side-effect of the bypass used.
Ok!
