### ISSUE TITLE
Skip_TPM_Check_on_Dynamic_Update.cmd script doesn't work from build 22543 onwards

### ISSUE THREAD

**Issue by ripkaby** [AveYo/MediaCreationTool.bat#111]
The script used to work on older builds, but since 22543, windows installer still prompts lack of tpm every time there is a build update. Tried uninstalling and reinstalling the script. Had to resort to using [Quick_11_iso_esd_wim_TPM_toggle.bat] to update.

**Comment by AveYo** [comment]
works fine here. maybe it's an issue with your antivirus blocking it?

**Comment by Nirob3x** [comment]
@ripkaby just turn off your windows defender or any other antivirus, it will work.  and @AveYo  Thanks for the script.

**Comment by ripkaby** [comment]
Just tested with upgrading to 22567.1 again still with no luck. Antivirus (disabled) was disabled, script was rerun and still was greeted with "The PC must support TPM 2.0" message. Is there anything I should attach here? Thanks!

**Comment by AveYo** [comment]
The script definitely still works with 22567, I have a dozen of confirmations, including my own.  

You can provide `C:\$WINDOWS.~BT\Sources\Panther` logs (zip / attach / share them)

**Comment by ripkaby** [comment]
[Panther.zip](https://github.com/AveYo/MediaCreationTool.bat/files/8183072/Panther.zip)

Thanks very much. Just tried again and still didn't work.

**Comment by AveYo** [comment]
No trace of bypass script running.  
Report to the dumbers at Bitdefender as a false-positive with the [script url](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd)  
The bypass is all registry-based, under: 
`HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SetupHost.exe`  
No idea if you can whitelist that yourself

**Comment by ripkaby** [comment]
Can't even find this key in regedit lol... Is there any way I can manually add the key? Still figuring out if I can whitelist a registry

**Comment by ripkaby** [comment]
Just tried again with defender off, bitdefender uninstalled and rerun the script multiple times after fresh reboot and still with no luck...
Am going to wait for a few more days before resorting to just upgrading via complete iso
[Panther.zip](https://github.com/AveYo/MediaCreationTool.bat/files/8188060/Panther.zip)

**Comment by AveYo** [comment]
Same. 
Bitdefender is not even uninstalled in this instance. 
Did you restart your machine? (might also want to disable Fast Startup).

I can't really help with your configuration blocking the script.

**Comment by ripkaby** [comment]
So, interesting update
Made sure Bitdefender is uninstalled (which already is), fresh reboot, defender disabled, rerun the script twice.
Still had the error.

Then I run the script again to uninstall it. (Green installed prompt and pressed a key to uninstall)
Performed windows update again, still with defender disabled and not yet restarted.
This time, **Windows Server Setup error** prompted me that it could not determine the version of windows I'm running, but after closing the window. it just went on and install the update to next build anyway.

So... Problem solved? Script somehow work under half uninstalled environment...
Thanks @AveYo very much, I can finally easily upgrade to next build again!
Will attach panther logs later

**Comment by AveYo** [comment]
Guess so. I would re-run the script.  
Just remember, Green Prompt = bypass installed. Magenta = bypass uninstalled. You want green obviously

**Comment by ripkaby** [comment]
Quick update:
BSOD during upgrade, had to re do everything.
The script is reported to be uninstalled (Magenta). Proceeded to download update again and succeeded. Guess somehow for my PC, the installation message is inverted?...
Happy to say it now works like how it used to.
Will attach panther logs later (if no BSOD happens again lol ;-;)

**Comment by ripkaby** [comment]
Everything worked after several bsods. No logs available, windows deleted them

**Comment by AveYo** [comment]
I haven't seen a BSOD in what is now more than 100 installs, most on separate devices.  
It screams bad drivers (be it device drivers, or kernel drivers like for example those used by antivirus software). 
Great you managed to brute-force it ;)
