### ISSUE TITLE
setup.exe patching...

### ISSUE THREAD

**Issue by PaulNevada** [AveYo/MediaCreationTool.bat#112]
Is there any way to patch the data so, that it'll allow to install os to the usb devices?

**Comment by nguyenthienminh** [comment]
Seems like you can only use Enterprise to do that. Any other edition would just error out on logon, saying that "the user profile cannot be loaded".

**Comment by PaulNevada** [comment]
No, I am talking about the installation step...

**Comment by AveYo** [comment]
Windows To Go is discontinued since version 1903 (19H1) and removed from files in 2004 (20H1)  
I don't see what could be patched in setup to bring it back.

**Comment by PaulNevada** [comment]
Just to patch so, that the setup.exe running from a usb flash drive would allow to select the target disk which is a usb device!

**Comment by AveYo** [comment]
Would require tremendous effort for so little benefit, it's not a realistic task.

**Comment by PaulNevada** [comment]
Hm-m-m, I thought it would take not that much effort... Understood... Thanks!
