### ISSUE TITLE
Patch already written USB

### ISSUE THREAD

**Issue by Bug38** [AveYo/MediaCreationTool.bat#119]
Is it possible to patch an already created USB ? I've used the standard MCT11 to create a USB-ESD media.
Your script allows to patch ESD files, but I can't figure how to patch the USB-ESD directly, is it possible ?

**Comment by AveYo** [comment]
browse to usb-drive-letter\sources\install.esd - send to - Quick_11_iso_esd_wim_TPM_toggle

**Comment by Bug38** [comment]
Nice, thank you for the quick answer !
