### ISSUE TITLE
TPM bypass breaking Windows Update

### ISSUE THREAD

**Issue by mobilegmYT** [AveYo/MediaCreationTool.bat#120]
The script automatically applied the TPM bypass since I was using a unsupported device without TPM. From the README, it seems like the bypass for a in-place upgrade is just changing the product to be Windows Server, which works fine. A side effect of this is that it creates group policy changes, which means that all Windows Updates you receive in the future will fail to download because the group policy seems to point by default to a nonexistent local server (I assume it's because most organizations using Windows Server will host their own server to serve updates).

**Comment by AveYo** [comment]
Tested with 11 Dev, so there have been quite a lot of normal updates and feature upgrades, without further intervention other than opening Settings - Windows Update - Check.  
Nor the script, nor windows update applies such policy / registry equivalent by default.  

But I do not exclude something breaking lately (a lot has broken in the last 3 dev builds).
It's quite relevant to mention the Edition you've used.

**Comment by mobilegmYT** [comment]
> Tested with 11 Dev, so there have been quite a lot of normal updates and feature upgrades, without further intervention other than opening Settings - Windows Update - Check. Nor the script, nor windows update applies such policy / registry equivalent by default.
> 
> But I do not exclude something breaking lately (a lot has broken in the last 3 dev builds). It's quite relevant to mention the Edition you've used.

My current version is 21H1(22000.527). One note I should add if that when I get a new update available, cululiative or a major update like 22H1, the update seems to go successfully but my version doesn't seem to change.

**Comment by AveYo** [comment]
> the Edition you've used

Dude..  

> 21H1(22000.527)  

Dude..

22000.493 is the actual build windows 11 would automatically update to. 

[Windows 11 update history](https://support.microsoft.com/en-us/topic/windows-11-update-history-a19cd327-b57f-44b9-84e0-26ced7109ba9)  

You're running the last released update. It's even a preview one, so entirely optional.  

And you somehow complain that because of the script you can't update? Get your facts straight.

**Comment by mobilegmYT** [comment]
Oh sorry, I thought I was on a old version, since my PC is still missing some of the new features that came in the latest windows 11 upgrade like WSA and the weather widget.

**Comment by AveYo** [comment]
Microsoft does A/B testing with those, so it's random / region-based.
Using US as region and language helps move up the queue, but it's not a guarantee.

**Comment by mobilegmYT** [comment]
> Microsoft does A/B testing with those, so it's random / region-based. Using US as region and language helps move up the queue, but it's not a guarantee.

Oh, didn't know that. Thanks!
