### ISSUE TITLE
Ask about only processor doesnt supported

### ISSUE THREAD

**Issue by nmbayu** [AveYo/MediaCreationTool.bat#121]
My laptop doesnt supported by windows 11 only processor (AMD A8 7410) everything was green only processor has red, is it safe to use this tool? Does this tool can update directly from Microsoft update (windows update) without ISO, like supported device? 
Thank you

**Comment by dudefoxlive** [comment]
No this tool creates an iso file that you can use to upgrade the system. You can write it to a usb drive or double click the iso to virtually mount it in windows and run it directly from there.

Though i have heard in beta build of 11 right now you will get a water mark that states your machine does not meet requirements. Not sure if or when this will come to the stable public release of 11.

**Comment by AveYo** [comment]
> My laptop doesnt supported by windows 11 only processor (AMD A8 7410) everything was green only processor has red, is it safe to use this tool? Does this tool can update directly from Microsoft update (windows update) without ISO, like supported device? Thank you

There's a whole section under readme called:  
**Get RP/BETA/DEV 11 via Windows Update on "unsupported" hardware**
