### ISSUE TITLE
Boot Camp - Upgrading Win 10 to Win 11 - Stuck at 56/57%

### ISSUE THREAD

**Issue by yungjoao** [AveYo/MediaCreationTool.bat#127]
Hello, I am trying to update from Win 10 to 11 on my Mac, Intel chip, and it always get stuck at 56 or 57%, already tried to do it 5 or 6 times, already restarted the PC, and still getting stuck. What can I do?

Thank you!

**Comment by AveYo** [comment]
Stuck how? can you screenshot it?
Do you have enough free space on `C:\`?

Might want to wait a bit because I am updating the script atm,
enabling Dynamic Update so you get latest release build directly - 22000.556 atm.

**Comment by yungjoao** [comment]
> Stuck how? can you screenshot it? Do you have enough free space on `C:\`?
> 
> Might want to wait a bit because I am updating the script atm, enabling Dynamic Update so you get latest release build directly - 22000.556 atm.

<img width="762" alt="Capture" src="https://user-images.githubusercontent.com/73616814/158429310-3236d750-eba0-41e2-ada3-cfc24a383ffd.PNG">

<img width="527" alt="2" src="https://user-images.githubusercontent.com/73616814/158429445-11bc9485-f7a1-439a-b2bf-5dbfb30c02c6.PNG">


Yes, I have 100gb left free!
It just hangs on 56% and stays there, doesn't do anything else on the Downloading Windows 11 part.
I just saw now that it is giving me an error after closing the installer.

**Comment by AveYo** [comment]
Hmm, your accented username might cause some issues.
Can you copy-paste it in a reply here (the `Joao` part)

**Comment by yungjoao** [comment]
Makes all sense, already had some issues before because of that, sometimes I hate my name.
Ofc! Here it is:

`João`

**Comment by AveYo** [comment]
On second look, your issue happens with the setup process itself.
The script does nothing but wait for it to finish at that stage.

Most likely your network timed out, then power saving kicked in and suspended the setup process, causing the hang. Or some other stuff interfering.

I would recommend not running other programs while the script runs.
And switching to High Performance power profile to prevent idling.

In any case, do try the updated script I just pushed.

**Comment by AveYo** [comment]
On third look, yeah the script has been cascade broken over the weekend.
I have pushed a more stable, robust script
Feel free to reopen if you bump into the issue again.
