### ISSUE TITLE
Can't find Sources

### ISSUE THREAD

**Issue by SkyQuake1010** [AveYo/MediaCreationTool.bat#130]
Firstly, thanks for this awesome script!

I've used it successfully in the past, but with the latest release I'm encountering the following scenario.

1. Chose to upgrade to Win11.
2. Media is eventually created.
3. After media is create, the program can't find "Sources".
4. The program then continues stating "Upgrading".
5. A few seconds later, the program exits.

This is being done on a virtual machine.

Once again, thank you.

**Comment by AveYo** [comment]
Sorry, regression trying to fix another issue that proved to be 100% unrelated to the script.
Should be fixed now!

**Comment by AveYo** [comment]
@SkyQuake1010, try the updated script, it's back to being stable!
