### ISSUE TITLE
Cannot find downloaded Media

### ISSUE THREAD

**Issue by ridgegate** [AveYo/MediaCreationTool.bat#131]
Hi

I could not find the downloaded media anywhere on my computer. I have checked the current directory and C drive. Any other places that the Auto ISO might be downloading the media to? I checked C:\ESD folder and folder shown on the terminal (E:\11 21H2...iso) but the ISO is nowhere to be found. Thanks

![result](https://user-images.githubusercontent.com/20883705/159130129-e8833c05-c760-4c2f-8fbe-6e2c8728a911.jpg)

**Comment by mart-hill** [comment]
Yup, I also noticed that the script creates ISO file just to delete it immediately afterwards (at least in Auto ISO mode, but I saw it happen in Select mode as well).

**Comment by AveYo** [comment]
yep, the regressed regression regressing regressed ;(
will fix later once and for all

**Comment by AveYo** [comment]
@ridgegate, @mart-hill, try the updated script, it's back to being stable!
