### ISSUE TITLE
unable to connect to windows server.

### ISSUE THREAD

**Issue by ShyCode-analyst** [AveYo/MediaCreationTool.bat#135]
This error pops up for me, I can't follow.

I use the update method.

could i be doing something wrong?

**Comment by AveYo** [comment]
What is your existing OS?  
What is Settings - Windows Update say it's doing? Can you screenshot it? 
At what stage you get the issue? Can you screenshot it?

**Comment by AveYo** [comment]
Feel  free to reopen if you have extra info to add
