### ISSUE TITLE
feature: multilingual-support

### ISSUE THREAD

**Issue by lukastribus** [AveYo/MediaCreationTool.bat#139]
Hello,

is there any chance multilingual support could be implemented in MCT, as per:

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-multilingual-support-to-windows-setup?view=windows-11

Thank you!

**Comment by AveYo** [comment]
@lukastribus, 
Not really. MCT creates highly compressed install.esd media, that is not serviceable in that way.  
MUI requires install.wim modding. 
You're better served by other solutions like [W10MUI](https://github.com/abbodi1406/WHD/tree/master/scripts) - and even with that, it's a tedious job.
