### ISSUE TITLE
Cannot upgrade to Windows 11

### ISSUE THREAD

**Issue by vlOd2** [AveYo/MediaCreationTool.bat#141]
Hello,

I've been trying for a few hours to install Windows 11 on Windows 10 21H2
I've followed the steps in the `bypass11` folder under `Get 11 via Windows Update on "unsupported" hardware`.
Windows Update gets the Windows 11 update, and gets stuck at `0% Downloading` for a few minutes, then reports `There were problems downloading some updates, but we'll try again later. If you keep seeing this, try searching the web or contacting support for help. This error code might help: (0xc8000402)`
The `MediaCreationTool.bat` Auto-Upgrade on Windows 11 reports the same error code.
Am I doing something wrong? 

NOTE: I have some Windows Update group policy rules, but they are to disable automatic updates, I will try to disable them then send an update
![Screenshot_1](https://user-images.githubusercontent.com/66838724/163722219-12653742-d607-4ee7-9491-328766f78ef8.png)

**Comment by AveYo** [comment]
How could it work if you're hindering WU with full force?  
_Specifies target server.._ simply nukes all WU updates, _Target release version_ as well.
Revert all your configured WU policies and try again.

**Comment by darkstudio** [comment]
WIndows 11 not available anymore. i doesn't find the download link.
![image](https://user-images.githubusercontent.com/6309663/164538898-3e4ba651-b9bc-4a89-b84e-07e27cb73a32.png)

**Comment by AveYo** [comment]
It's probably under maintenance, if you go directly to microsoft site it's not available there either  
[https://www.reddit.com/r/Windows11/comments/u8tj1f/unable_to_download_windows_11_creation_tool/](https://www.reddit.com/r/Windows11/comments/u8tj1f/unable_to_download_windows_11_creation_tool/)  
There might be new esd releases in preparation for the upcoming End-Of-Support for more versions.
