### ISSUE TITLE
Can't login after successful auto upgrade

### ISSUE THREAD

**Issue by lucaslannes** [AveYo/MediaCreationTool.bat#142]
First thanks for the awesome tool.

So, after the auto upgrade I'm now on the login screen with "Other user" displayed and some sign-in options below (local/domain account and Microsoft account), but I don't know how to login because no one of the options are working.

I set on the installation process to delete everything (accounts, settings and files).

There is some "default user" that I can use to perform the login? Or there is no solution for me? 👀

![16503293832288377859465264894643](https://user-images.githubusercontent.com/54950765/163898831-17a0f483-f5e8-459e-82bc-01e6e67ae081.jpg)

![16503294660107144511692548633276](https://user-images.githubusercontent.com/54950765/163898952-df889813-5e9d-455a-b56f-e420503797f7.jpg)

**Comment by AveYo** [comment]
> I set on the installation process to delete everything (accounts, settings and files).

**Why, tho?** 
That's no longer an upgrade, but -something-worse-than-clean-install-
You've instructed setup to clean everything including it's files,
so now you need to reinstall. 

Next time, do it properly when you want a clean install: boot from created media!

If you don't have one ready,
- extract iso to a folder, preferably not C:\
- then Start Menu - Power button - Shift + click Restart button to get into recovery menu
- then Troubleshoot - Command Prompt
- then enter: location-to-extracted-iso\setup

**Comment by lucaslannes** [comment]
Oh, man, you're right, I made a bad mistake.

Because I made a backup of all my files before start the upgrade, so I thought that a "clean upgrade" would be good.

So, just some questions:

- How I can extract the iso to a folder on the system if I can't access the file manager?
- The recovery menu - troubleshoot - command prompt is the way to access the file system?

Sorry for my poor knowledge about this proccess.

Anyways, I'll create a iso file using the Media Creation Tool from Microsoft to follow your instructions.

Just one more question, does it make sense first install Windows 10 on my notebook (because I have an "unsupported" hardware) and then upgrade to Windows 11 using your tool? Or can I directly install Windows 11 trought some iso file that skip the TPM and hardware stuff?

Maybe you can write this note on the README.md telling to the users don't choose the "Delete everything" option on the upgrade.

**Comment by AveYo** [comment]
You can directly use 11 ISO or **USB** created by this script, it has built-in bypass.
The Auto Upgrade preset (`auto.cmd`) don't even give a choice and sets to keep everything.
If you run `setup.exe` instead yourself, it's fully under your control.

As for your questions, it's not trivial to do it without the explorer file manager. 
I personally always have Total Commander somewhere on my usb sticks and hard drives, and can launch it under recovery command prompt to do various tasks like backup or extracting iso / archives. 
Maybe you could add it to a usb stick, then access it like: usb-drive-letter:\totalcmd\totalcmd64.exe

**Comment by lucaslannes** [comment]
I followed your instructions and created the ISO using your script.

But running the `setup.exe` and choosing one of the Windows versions I got the message that my system doesn't have the minimum system requirements.

Below is my USB stick with the ISO files:

![16504162581178248466953977281818](https://user-images.githubusercontent.com/54950765/164125814-2037eb23-2a60-4875-9b2c-126d4a238b6c.jpg)

I have another stick with Total Commander and the pure ISO file too:

![16504163912024478676499225011445](https://user-images.githubusercontent.com/54950765/164126012-f841d85a-33a1-4ded-a9c7-b8abdfdb15cd.jpg)

The bypass isn't working?

**Comment by AveYo** [comment]
@lucaslannes, 
Bypass works when you boot from the media.
That means, take the iso, make a bootable USB or DVD out of it (that's why script offers a USB choice).
But no problem, you can still bypass what you have by entering this in cmd:
```bat
cmd /c for %s in (TPM SecureBoot RAM Storage CPU) do reg add HKLM\SYSTEM\Setup\LabConfig /v Bypas%sCheck /d 1 /t reg_dword /f
```
and then running setup.exe

**Comment by lucaslannes** [comment]
@AveYo, you helped me a lot. Thanks for all the support.

I entered the command in CMD to bypass the checks and the `setup.exe` finally worked without impediments.

Just to notice, the command have a typo in the `Bypas%sCheck` that has to be `Bypass%sCheck`.

```bash
cmd /c for %s in (TPM SecureBoot RAM Storage CPU) do reg add HKLM\SYSTEM\Setup\LabConfig /v Bypass%sCheck /d 1 /t reg_dword /f
```

God bless you 🙌
