### ISSUE TITLE
Windows Defender block Skip TPM Check v7

### ISSUE THREAD

**Issue by nondetect** [AveYo/MediaCreationTool.bat#144]
When Windows update starting download new build Defender blocks it with this threat on screenshot.  I checked that from Windows 10 20H2 to latest. Maybe it's new updated Windows Defender bases. Before script works pretty well 
![Windows Defender](https://i.imgur.com/kZNXqd8.png)
[Link from screenshot](https://go.microsoft.com/fwlink/?linkid=142185&name=Behavior:Win32/Powessere.SA&threatid=2147796557)

Temporary solution, before start updating Turn off in Windows Defender "Real-time protection" and "Tamper Protection" setting

**Comment by renschmid** [comment]
I can confirm this issue and work around it by turning off "Real-time protection" only.

**Comment by AveYo** [comment]
Defender false and fake positive strikes again? 
OK.
Reject PowerShell. Return to ~~Monke~~ CMD.
_Skip TPM Check on Dynamic Update **V8**_ on the way.

**Comment by AveYo** [comment]
V8 is up!

**Comment by nondetect** [comment]
> V8 is up!

Check new version on w10 19042 and it's works. Just need change some "@echo on" and add "cls" for glance

**Comment by AveYo** [comment]
it's obviously more verbose on purpose ;)  
thanks for the feedback!

**Comment by AveYo** [comment]
and refined it in V9!  
verbose output commented, and adjusted the colors a bit
