### ISSUE TITLE
Missing version 2004

### ISSUE THREAD

**Issue by LoganDark** [AveYo/MediaCreationTool.bat#147]
I was [instructed by a Microsoft employee](https://github.com/microsoft/terminal/issues/13099#issuecomment-1133458066) that I would have to do an in-place upgrade in order to repair damage caused by [a command that they had provided indirectly](https://github.com/microsoft/terminal/issues/12534#issuecomment-1051338640) (found because I was told to just 'follow steps' [here](https://github.com/microsoft/terminal/issues/13099#issuecomment-1127840455)). I have Windows 10 2004 build 19041.928 (64-bit) and it looks like 2004 is conspicuously missing from this tool:

![image](https://user-images.githubusercontent.com/4723091/170256315-a5ca48dd-fa56-49fb-9041-a821486f7961.png)

Could you please add 2004 so I don't have to update any more than I need to?

Thanks :)

**Comment by AveYo** [comment]
20H1 = 2004 ;) H1, first half of the year, usually 4th month of the year, April release.
I've used 20H1 label to separate somehow the modern versions.
But now that 20H1 = 2004 is End Of Support, I will change the label to 2004 ;)

**Comment by LoganDark** [comment]
> 20H1 = 2004 ;) H1, first half of the year, usually 4th month of the year, April release. I've used 20H1 label to separate somehow the modern versions. But now that 20H1 = 2004 is End Of Support, I will change the label to 2004 ;)

My winver says 2004:

![image](https://user-images.githubusercontent.com/4723091/170288082-c76311b5-1a1d-4f85-9ea6-aef3964f3f0b.png)

Should 20H1 say 20H1 there?

**Comment by AveYo** [comment]
It was a simple question as well, no need to get worked up ;)
Microsoft inconsistencies are everywhere, including the monikers, but a simple google search would have shown 2004 = 20H1, that's all.
They were supposed to always release the H1 build in March, like the 1903 = 19H1. But with 2004 = 20H1 it got delayed to April. H2 builds are even worse.
2004 does stick out like a sore thumb, good thing it's End Of Support. I will rename it in the script like I said, in the next commit. Sorry for the confusion.

**Comment by LoganDark** [comment]
> a simple google search would have shown 2004 = 20H1, that's all.

I didn't know to search for that. I saw 20H1 and not 2004, and there's no reason I would've looked up "is 20H1 just 2004 in disguise" lol.

**Comment by LoganDark** [comment]
This downgraded my system from build 19041.928 to 19041.572 !!!

**Comment by AveYo** [comment]
**Via Windows update!**
It's a good thing it successfully downgraded to the very stable .572, that means whatever issues you faced are fixed.
But you see, the problem with staying on End Of Support versions, is that windows update will try to push the most recent one.
You can prevent that with yet another script, [windows_feature_update_toggle.bat](https://pastebin.com/EcLB14hg) 
Once feature upgrades are blocked, then your OS will only update up to last 2004 version for your edition (Education and Enterprise 19041.1415).

**Comment by LoganDark** [comment]
> It's a good thing it successfully downgraded to the very stable .572, that means whatever issues you faced are fixed.

Only some of them unfortunately. (you can see my comment [here](https://github.com/microsoft/terminal/issues/13099#issuecomment-1138459416))

> Once feature upgrades are blocked, then your OS will only update up to last 2004 version for your edition (Education and Enterprise 19041.1415).

Is there any way to get back to 19041.928 specifically? WUMGR isn't working anymore for some reason.

**Comment by AveYo** [comment]
Yes, you can manually download and install it from microsoft catalog:
https://www.catalog.update.microsoft.com/Search.aspx?q=KB5001330
get the `2021-04 Cumulative Update for Windows 10 Version 2004 for x64-based Systems (KB5001330)`

You can also create an iso for this build via [uupdump](https://uupdump.net/selectlang.php?id=6c5da194-603e-4339-bec5-92b021324cae)
