### ISSUE TITLE
win 11 to win 10

### ISSUE THREAD

**Issue by ashuvax** [AveYo/MediaCreationTool.bat#160]
Hi Is there a way in your script to go back from Windows 11 to Windows 10?

**Comment by AveYo** [comment]
No. But I might add an experimental feature to do that in the next version. Stay tuned.

**Comment by ashuvax** [comment]
If already the best would be if it would be possible to leave all the software and files
This means that the files will not be deleted as in the update from Windows 10 to 11

**Comment by joey00797** [comment]
hi all
I tried to "update" from 11 to 10 to the latest build in the script (21H2).
and got a relatively good result)
in the end I got a clean install, all my files were deleted (it's good that this is a test pc))

**Comment by AveYo** [comment]
That's obviously have been an unsupported scenario since forever and you are prompted that fact (data will be gone).
If I implement a workaround, it will be quite hackish and not at all guaranteed to work, so it's to be used as a last resort. So. Make. Backups.
