### ISSUE TITLE
w10 LTSC(LTSB)

### ISSUE THREAD

**Issue by joey00797** [AveYo/MediaCreationTool.bat#164]
Hey
tell me please
1. Will there be support for the LTSC version?)
1.1.Is it possible to force add, for a clean install or update from a script.
and 2nd question, off topic, your script uses powershell commands. Is this some hybrid of cmd and powershell?
can i read somewhere how to do it? or maybe you can give an example of a simple script in cmd using powershell)
for example, I have a script with a question and options, and the options are executed under the guidance of a powershell) but I have such a garden in this script that just delete the script and forget it))

**Comment by AveYo** [comment]
No. Microsoft does not publicly share LTSC version.

Most of my scripts are hybrid, for convenience. Sometimes it's powershell in a cmd container, other times cmd in a powershell one, or something intertwined like this one. I come up with my own hybrid formats, but it's quite easy to implement for yourself. For example, MCT is a batch script including many areas of powershell code. That code is read and executed into powershell via a single line such as:
`set "0=%~f0" & powershell -nop -c "iex ([io.file]::ReadAllText($env:0) -split '[:]Assisted_MCT')[1];"`
The actual code is between two `:Assisted_MCT` labels doubling-down as tags. Obviously I can have many more tags for different functionality requiring powershell.

**Comment by AveYo** [comment]
1. what good would that do? (adding your own iso file)

2. yes

3. what do you need to know except it works, without the shortcomings of powershell or vbs  
- it's the fastest, it's a mere 2-lines, and it's av-friendly
- emulates the native right-click Run as Admin context-menu behavior while working from any path (call ..) and enabling high priority (/high), disabling pesky cmd autoruns (/d) and forcing cmd extensions on (/x)
- it's portable (does not alter the default .bat .cmd etc entries but creates a new class i.e. extension ".Admin") to pass the commandline unadulterated

**Comment by joey00797** [comment]
1. this is a good question) probably the benefit is to be able to install / reinstall without the Internet and without any questions ... by adding an already downloaded image (possibly not only LTSC, but also, for example, w10pro

3. I'm just learning but I'm extremely interested)
can I send you my script for analysis, or maybe for instructions, please)

I'm sorry in advance that I madly stole your parts of the code and used them so clumsily =)

**Comment by AveYo** [comment]
I won't be able to help out with that, my time is booked 2 lifetimes in advance ;)

**Comment by joey00797** [comment]
I understand =)
it's okay, it's enough that you don't mind being used your code)
