### ISSUE TITLE
Bootcamp year 8522

### ISSUE THREAD

**Issue by Etxe73** [AveYo/MediaCreationTool.bat#166]
I installed windows 11 in bootcamp with this script, and then windows does not start or it does in the year 8522. I have 2 macs where I have installed windows 11 and the same thing has happened in both (iMac 2020 and Mac Mini 2018). It only starts normal if the power cable is not unplugged after install windows. The mac side alwais run in date.I have reverted to windows 10 and formatted the mac and the same thing happens with windows 10. After unplugging the power cable it either doesn't boot or it boots in the year 8522. Something has destroyed the mac for bootcamp on 2 different macs so it's not by chance. Any ideas?

**Comment by JonnyTech** [comment]
https://discussions-kr-prz.apple.com/en/thread/253967767
