### ISSUE TITLE
AveYo's promise ...

### ISSUE THREAD

**Issue by MadSochi** [AveYo/MediaCreationTool.bat#171]
AveYo in January you promised to update Dota No-Bling and then you disappeared.
Where are you?
We waiting for half of year.
And STILL waiting.
It's a beautiful tool to disable all of that shiny skins and annoying sound phrases in chat.
I'm so tired from all of that. Wanna to play always with STANDART DEFAULT lookable heroes.

Please come back and make your promise come true.

**Comment by ethical2012** [comment]
@MadSochi The issues section is not a place to demand and complain about things.  It is for REAL issues.   From past posts on projects it appears you have gotten used to thinking that is what this section is used for.  Please kindly keep this in mind in the future on projects you are interested in.
