### ISSUE TITLE
ERROR: Access is denied.

### ISSUE THREAD

**Issue by liaolunhui** [AveYo/MediaCreationTool.bat#174]
By running Skip_TPM_Check_on_Dynamic_Update.cmd, get those error

ERROR: Access is denied.
 Skip TPM Check on Dynamic Update V9+  INSTALLED  run again to remove

Waiting for 6 seconds, press a key to continue ...

**Comment by AveYo** [comment]
Something is blocking the script, probably when setting IFEO override.  
Check your antivirus alerts, whitelist the script.
