### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by johlkien** [AveYo/MediaCreationTool.bat#177]
MediaCreationTool.bat opens then closes right away. When the zip file downloads and extracts it only contains a file named ".. MediaCreationTool.bat ..md" After renaming it to MediaCreationTool.bat so it will run it closes. Trying to open via command prompt gives me this:

![image](https://user-images.githubusercontent.com/6784664/183506444-d5210361-d95e-4485-aef9-e12f247e40a6.png)

Then when I try the suggestions, I get this
![image](https://user-images.githubusercontent.com/6784664/183506831-2cec0f6b-f411-45ee-9992-c98a2491d82d.png)

**Comment by AveYo** [comment]
are you somehow using the old gist? don't. 
https://github.com/AveYo/MediaCreationTool.bat
at the top click the green button labeled Code, and then `Download ZIP`
- open the resulting `MediaCreationTool.bat-main.zip` 
- click `MediaCreationTool.bat` and choose `Run`  

or view https://github.com/AveYo/MediaCreationTool.bat/blob/main/MediaCreationTool.bat
at the top click `Raw` then press `Ctrl` + `S` (Browser - Save), select File type = All files
