### ISSUE TITLE
Cant download Windows 10 1803.

### ISSUE THREAD

**Issue by randomguyfromAustria** [AveYo/MediaCreationTool.bat#181]
Hello.
I have a issue with this tool.
I cant download 1803, it says download failed and then the media creation tool doesnt open. Please fix it.

![cmd_YeXVtbPY4w](https://user-images.githubusercontent.com/95542560/186127101-8cd075db-15a7-4573-bde8-10d727470b06.png)

**Comment by AveYo** [comment]
Url was removed by microsoft
A quick fix before I publish the next update is to replace it with 1809 version:
lines 199-200:
```bat
set "VER=17134" & set "VID=1803" & set "CB=17134.112.180619-1212.rs4_release_svc_refresh" & set "CT=2018/07/" & set "CC=1.2"
set "EXE=https://software-download.microsoft.com/download/pr/MediaCreationTool1803.exe"
```
to
```bat
set "VER=17134" & set "VID=1803" & set "CB=17134.112.180619-1212.rs4_release_svc_refresh" & set "CT=2018/07/" & set "CC=1.3"
set "EXE=https://software-download.microsoft.com/download/pr/MediaCreationTool1809.exe"
```

**Comment by Pafyz** [comment]
> Url was removed by microsoft A quick fix before I publish the next update is to replace it with 1809 version. line 198:
> 
> ```batchfile
> set "VER=17134" & set "VID=1803" & set "CB=17134.112.180619-1212.rs4_release_svc_refresh" & set "CT=2018/07/" & set "CC=1.2"
> ```
> 
> to
> 
> ```batchfile
> set "VER=17134" & set "VID=1803" & set "CB=17134.112.180619-1212.rs4_release_svc_refresh" & set "CT=2018/07/" & set "CC=1.3"
> ```
> 
> line 200:
> 
> ```batchfile
> set "EXE=https://software-download.microsoft.com/download/pr/MediaCreationTool1803.exe"
> ```
> 
> to
> 
> ```batchfile
> set "EXE=https://software-download.microsoft.com/download/pr/MediaCreationTool1809.exe"
> ```

Hey! Can u please make such a guide for 21H2?

**Comment by AveYo** [comment]
21H2 works just fine. Are you located in RU? Might wanna use a VPN then.

**Comment by randomguyfromAustria** [comment]
No, i am located in Austria.
