### ISSUE TITLE
I can't download your archive from Github

### ISSUE THREAD

**Issue by YobaItem** [AveYo/MediaCreationTool.bat#182]
Most likely the reason is that I live in Russia, is there an opportunity to download your project in a different way?
Thank you in advance! (Spasibo).

**Comment by AveYo** [comment]
does gitlab work? if not, propose something and I will try to mirror it for the next update

**Comment by YobaItem** [comment]
I will try to download from gitlab, I will definitely let you know if it works. You can also upload the project to Google Drive until we are denied access.

**Comment by YobaItem** [comment]
The archive was downloaded thanks, but when you try to burn an image of Windows 10 to USB, the first window starts, but before selecting a flash drive, it simply closes with this error.
![image](https://user-images.githubusercontent.com/112122517/186764455-f53c37a9-d993-45df-927a-9cb0a8a0f3d1.png)

**Comment by YobaItem** [comment]
Hello, I solved my problem and was able to write the image to a flash drive, thanks for your work and the public project. Also can I write a short guide for people who might have the same problem as me? The guide will be in Russian and English.

**Comment by AveYo** [comment]
Sure! You could also do it as a discussion entry here. 

https://github.com/AveYo/MediaCreationTool.bat/discussions

If it's something I can address in the script itself I will implement it.

**Comment by YobaItem** [comment]
The problem is not in your script, but in the fact that the version of Windows 21H2 for Russian citizens fell under sanctions, apparently like the following versions. The problem is from Microsoft.
