### ISSUE TITLE
Allow upgrading without loss of data.

### ISSUE THREAD

**Issue by rokejulianlockhart** [AveYo/MediaCreationTool.bat#188]
When I upgraded, I was forced by the MediaCreationTool to “remove everything”, apparently because my installation was “installed in an unsupported location, or [something else]”. I merely installed the most recent Insiders Edition via the ISO provided into VirtualBox with the necessary LabConfig registry modification applied, so it should not be configured so unusually that upgrading whilst retaining present information is impossible or difficult.

**Comment by AveYo** [comment]
Microsoft does not support downgrades. 
It technically works across the same master build, such as 1903-1909, or 20H1-20H2-21H1-21H2. Haven't tested yet 22H2 (19045) but should be in the same family.  

The jump to 11 is massive, specially if it's 22H2-based or above. Even with a compatibility workaround, there are high chances of broken shell / explorer / apps after the downgrade.

The next script version will probably facilitate downgrades, but only to the previous range - so, from 25xxx to 22621, from 22621 to 22000, from 22000 to 19xxx, not just latest 11 dev --> windows 10.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I hadn't realized that it was a downgrade.
