### ISSUE TITLE
After upgrade, no setup appears.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [AveYo/MediaCreationTool.bat#189]
I was plonked into the lock-screen, and the credentials for my Microsoft account are not accepted. I suppose that this is expected, because I have not been able to add an account to this installation. How am I to configure this installation without the setup screen...?

**Comment by RokeJulianLockhart** [comment]
@AveYo, why https://github.com/AveYo/MediaCreationTool.bat/issues/189#event-11197007666?

**Comment by AveYo** [comment]
Cannot replicate, sounds similar to #154 and #237
I have closed many old issues to try and manage this project again.

**Comment by RokeJulianLockhart** [comment]
I don't intend to use this any time soon, and don't recall what occurred, so I'll close this as unplanned.
