### ISSUE TITLE
Window install failed

### ISSUE THREAD

**Issue by Taran986** [AveYo/MediaCreationTool.bat#191]
I have been trying to upgrade windows 11 on unsupported hardware but after downloading ISO automatically it starts install then whole screen turns blue with written **Windows is installing 0%** then it stops and a dialog box appears saying **_couldn't install Windows_**.

**Comment by garybulah** [comment]
can'f install windows 11 on pc

**Comment by AveYo** [comment]
Upgrades can fail for many reasons, it's not something to blame on the MCT script.
Try doing a repair-install (in-place upgrade) with your current windows version, then try again.
Setup logs are saved in `C:\$Windows.~WS\Sources\Panther\` might want to check `setupact.log` and `setuperr.log` for hints on why does it fails for you.
