### ISSUE TITLE
Support for 22H2

### ISSUE THREAD

**Issue by johnkristian** [AveYo/MediaCreationTool.bat#194]
Hi

Thank you so much for really nice work! 
Win 11 22H2 is out. And it seems to be even more bitchy about TPM etc. than previous builds. 
When/how will the tool get support for it?

John

**Comment by AveYo** [comment]
Probably tomorrow!

**Comment by frixo3190** [comment]
yes, I've TMP but an old proc (Ryzen 7 first Gen :P ) , and no update W11 22H2, how to do to force it ?

**Comment by dbkblk** [comment]
> yes, I've TMP but an old proc (Ryzen 7 first Gen :P ) , and no update W11 22H2, how to do to force it ?

It worked for me using the "Skip TPM check" script and updating from the ISO!

**Comment by frixo3190** [comment]
I will try
Thanks

**Comment by 5460** [comment]
> I confirm this method works !

After running Skip_TPM_Check_on_Dynamic_Update.cmd, the setup becomes [Windows Server] setup. I didn't proceed. By removing Skip_TPM, the setup turns back to Windows 11 setup.

**Comment by frixo3190** [comment]
Me too I've noticed that, but just ignore it, it will install w11

look my sys info

![image](https://user-images.githubusercontent.com/23532434/191539358-994ed686-4880-4247-821a-b2b3df9da9f0.png)

**Comment by x9nico** [comment]
> Probably tomorrow!

Hey! Any news about it ?

**Comment by d1stru3t0r** [comment]
Having the same problem. I have an FX 9830P laptop for university stuff with TPM2/Secure Boot/Everything supported except CPU. I have W11 21H2 right now, and I wanted to upgrade to 22H2 but there isn't any way to simply just upgrade. Regedit with UnsupportedTPMOrCPU doesnt work, and neither any stuff from here, Windows search never shows the update and W11InstallationAssistant shows that my PC isn't compatible (thru Windows Health App). Also, I can't update for my friend with AMD FX :P 

Hope the next update will fix it soon :D

**Comment by jnxme1** [comment]
I cannot upgrade from an unsupported Windows 11 21h2 version 22h2 version laptop system this way. The bypass method worked on my desktop computer. I don't want to format my laptop. Could you please update this as soon as possible? Good work.

**Comment by fleetimee** [comment]
> I cannot upgrade from an unsupported Windows 11 21h2 version 22h2 version laptop system this way. The bypass method worked on my desktop computer. I don't want to format my laptop. Could you please update this as soon as possible? Good work.

Dude be patient holy moly 🤣🤣

**Comment by jnxme1** [comment]
I just said my problem.Sorry if it seemed impatient and I was misunderstood.I appreciate the work done.
![2022-09-21_13h24_52](https://user-images.githubusercontent.com/114142851/191765419-585f92c9-ab3f-4db7-bff2-81dae992501d.png)

![2022-09-22_16h43_27](https://user-images.githubusercontent.com/114142851/191765742-83855592-4d16-42a7-83f0-e20208eed74d.png)

**Comment by frixo3190** [comment]
Woo, 4gb ram is very few

**Comment by Coresi7** [comment]
Thank you! Works like a charm for 22h2!

**Comment by d1stru3t0r** [comment]
> Thank you! Works like a charm for 22h2!

For update? How?

**Comment by tet666** [comment]
Any news?

**Comment by jnxme1** [comment]
> Bu benim Masaüstüm ![2022-09-22_17h15_10](https://user-images.githubusercontent.com/114142851/191771638-5cc3ef39-b2d2-4acd-afcd-ec73e4468e3c.png)

If you want to upgrade from Windows 11 21h2 to 22h2 while keeping your files and programs from an unsupported computer like me, you can try it.

1) In Regedit > Computer\HKEY_LOCAL_MACHINE\SYSTEM\Setup\MoSetup > add the key "AllowUpgradesWithUnsupportedTPMOrCPU" and enter its value as 1.
![2022-09-23_20h20_38](https://user-images.githubusercontent.com/114142851/192023497-8693c777-97b2-487f-8eeb-ad61042bd2aa.png)

2) MediaCreationTool.bat/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd"
Run the file as administrator and when you see **"REMOVED**" go to step 3

![2022-09-23_21h04_22](https://user-images.githubusercontent.com/114142851/192029952-25024167-2c4c-402b-88ea-5416b89f26c9.png)

[3)](url  https://www.mediafire.com/file/qassh0co6scr8rh/appraiserres.zip/file ) Download the "Appraiserres.dll" file from the link and put it in the "source" folder of the Windows 11 22h2 ISO file you downloaded and replace it.Then you can start the upgrade from the setup section.It worked for me. I hope this method works for you too.

![2022-09-23_20h37_41](https://user-images.githubusercontent.com/114142851/192025494-415f1bf1-380b-466b-a642-6fad1c631e5c.png)

![2022-09-23_20h44_29](https://user-images.githubusercontent.com/114142851/192029521-29b921a3-079e-41f8-bbed-a388de3fc726.png)

![2022-09-23_21h01_28](https://user-images.githubusercontent.com/114142851/192029557-2cec9ffd-244e-4e13-aede-fbdd8ce22f10.png)

**Comment by d1stru3t0r** [comment]
Or just use this, afterwards the Windows 11 Instalation Assistant

https://github.com/InjectedPie/Windows-11-Inplace-Upgrade-unsupported-Hardware

**Comment by fleetimee** [comment]
> Or just use this, afterwards the Windows 11 Instalation Assistant
> 
> [InjectedPie/Windows-11-Inplace-Upgrade-unsupported-Hardware](https://github.com/InjectedPie/Windows-11-Inplace-Upgrade-unsupported-Hardware)

Actually works thanks

**Comment by markuznw** [comment]
> Or just use this, afterwards the Windows 11 Instalation Assistant
> 
> https://github.com/InjectedPie/Windows-11-Inplace-Upgrade-unsupported-Hardware

How do you do that? I tried it several times on my italian version and it keeps restarting the assistant and giving errors

**Comment by johnkristian** [comment]
Hi
Still can't see 22H2 as an option.
Am I doing something wrong?
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1437266/193175984-cefa1c3c-d219-4eba-a74d-b6813e850963.png">

**Comment by AveYo** [comment]
Not yet added, sorry.

**Comment by fcaronte** [comment]
i try this method and after some time it comeback to previous version and end giving me this error

![image](https://user-images.githubusercontent.com/26366403/196516719-45fb2b62-eeca-4b6a-b572-c72a86cf47b7.png)

**Comment by ElliotKillick** [comment]
If you're okay with WSL then I've just made a similar project called Mido: https://github.com/ElliotKillick/Mido

It's minimalist in that it's only for downloading the ISOs. Very clean and readable shell script. :)

Just an alternative for those who want something a bit simpler for VMs and such. Doesn't replace this project in any way.
