### ISSUE TITLE
Support For Auto Upgrade For Win 11 22H2

### ISSUE THREAD

**Issue by Aditya-Prakash-YT** [AveYo/MediaCreationTool.bat#200]
Any distinct support Win 11 22H2.

**Comment by TerryUK** [comment]
Well it does work if you read the other comments. Seems to be an issue for some but not all. 2:1 ratio of 3 people reported where they have it working. Think the issue is Microsoft packaging the ISO up which causes issues for some in the Windows Server. I didn't have an issue. Easy enough, did the job.

**Comment by Ta2i4** [comment]
Similar with #194

**Comment by Gipubla** [comment]
You can upgrade this way:
1. Download the new media creation tool from microsoft for W11 22H2 and create your Media (USB Drive or ISO)
2. Run [Skip_TPM_Check_on_Dynamic_Update.cmd](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd) provided by AveYo in the bypass11 Folder of this tool
3. Mount the ISO or open the USB Drive and Run the Setup.exe inside of it while Windows is running. 

Windows will start the upgrade to 22H2 without cheking for System Requirements. It says "Windows Server" on the installer but it isnt! Its regular W11 22H2.
![image](https://user-images.githubusercontent.com/114238202/192526735-4c22b900-3b17-4d68-839f-6c2c4f4406a0.png)
I did upgrade this way a couple of days ago and it works perfectly. 
I dont know how to get Media ready for a fresh clean install without Check for system requirements though.

**Comment by TerryUK** [comment]
> 
Yep... that's what I did on Sunday. No issues.

On 1. Just downloaded the ISO didn't create any bootable.

2. Yep

3. Yep. Just clicked on the ISO to start it off, does some fancy stuff of producing an E drive or something, ignore.

4. It worked !. Think Microsoft just packaged the ISO in old wrapping paper by the name of Windows Server 😉. Contents is W11H2. Strange for some people the wrapping paper sticks to the product inside 😐.

**Comment by UnclWish** [comment]
For me Windows Server installer on one of my comps writes that it can't run on my comp... On other comp all going normal.
This comp have much less RAM and old CPU. I'm use it for different tests (new updates and so on).
Does Windows Server have any RAM and CPU requirements?

**Comment by TerryUK** [comment]
Google reveals... don't know whether that makes sense if you compare the published spec with what your machines have.

**Comment by thanhdzzzzz** [comment]
> You can upgrade this way:
> 
> 1. Download the new media creation tool from microsoft for W11 22H2 and create your Media (USB Drive or ISO)
> 2. Run [Skip_TPM_Check_on_Dynamic_Update.cmd](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd) provided by AveYo in the bypass11 Folder of this tool
> 3. Mount the ISO or open the USB Drive and Run the Setup.exe inside of it while Windows is running.
> 
> Windows will start the upgrade to 22H2 without cheking for System Requirements. It says "Windows Server" on the installer but it isnt! Its regular W11 22H2. ![image](https://user-images.githubusercontent.com/114238202/192526735-4c22b900-3b17-4d68-839f-6c2c4f4406a0.png) I did upgrade this way a couple of days ago and it works perfectly. I dont know how to get Media ready for a fresh clean install without Check for system requirements though.


Thank you very much
It worked for me.
My computer configuration is old, so I can't install win 11.
I tried your way and it worked.

**Comment by TerryUK** [comment]
Also a Youtube Video link on the net which covers it:

https://youtu.be/HyeEeJ48sOc

The secrets been out a while but doesn't seem to work for everyone.  

People are re-publishing the instructions from the video. I didn't need to run the Skip_TPM_Check_on_Dynamic_Update.cmd as Administrator being the Administrator already, just click it.... you have to if installing the normal update on a compatible machine but that another story. The ISO doesn't need to be on a bootable USB, just click it.

**Comment by UnclWish** [comment]
After launching kip_TPM_Check_on_Dynamic_Update.cmd Windows Server installer works fine.

**Comment by bluefire369** [comment]
We can do a perflect **clean install** even with the latest & official Win 11 22H2 install, without any problems by using the [Quick_11_iso_esd_wim_TPM_toggle.bat](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Quick_11_iso_esd_wim_TPM_toggle.bat) tool.   
- Just place the tool in the 'Send to' menu, most probably here:
_%username%\AppData\Roaming\Microsoft\Windows\SendTo_
- Right click the downloaded ISO and then select > Send to > Quick_11_iso_esd_wim_TPM_toggle.bat

> The ISO file will be patched within seconds. It may show as Windows Server during the setup, but that's only to bypass the product key verification and other such requirements, but will always be the appropriate edition that you selected while downloading from the Microsoft website.

**Comment by Aditya-Prakash-YT** [comment]
> > 
> 
> Yep... that's what I did on Sunday. No issues.
> 
> On 1. Just downloaded the ISO didn't create any bootable.
> 
> 2. Yep
> 3. Yep. Just clicked on the ISO to start it off, does some fancy stuff of producing an E drive or something, ignore.
> 4. It worked !. Think Microsoft just packaged the ISO in old wrapping paper by the name of Windows Server 😉. Contents is W11 22H2. Strange for some people the wrapping paper sticks to the product inside 😐.

Did the same but it gave an error "Setup has failed to install Windows 11"

**Comment by TerryUK** [comment]
> > > 
> > 
> > 
> > Yep... that's what I did on Sunday. No issues.
> > On 1. Just downloaded the ISO didn't create any bootable.
> > 
> > 2. Yep
> > 3. Yep. Just clicked on the ISO to start it off, does some fancy stuff of producing an E drive or something, ignore.
> > 4. It worked !. Think Microsoft just packaged the ISO in old wrapping paper by the name of Windows Server 😉. Contents is W11 22H2. Strange for some people the wrapping paper sticks to the product inside 😐.
> 
> Did the same but it gave an error "Setup has failed to install Windows 11"

It's weird why it works for some but not for others. I put it down to the way the IOS file is packaged against the local language. 

You could try the DLL trick where you make one of the DLL files a null file, just delete the contents. That's an alternative. You can find that online. Many people use that but ofcourse might be hit by the same issue.  

This method but you open the DLL up in a text editor as save as null. Haven't tried it. Leave the file in place but remove what's in it... preferred to deleting now with this method.

https://nerdschalk.com/installing-windows-11-on-unsupported-hardware-how-to-remove-appraiserres-dll-to-bypass-requirements-when-using-setup/

**Comment by Aditya-Prakash-YT** [comment]
> > > > 
> > > 
> > > 
> > > Yep... that's what I did on Sunday. No issues.
> > > On 1. Just downloaded the ISO didn't create any bootable.
> > > 
> > > 2. Yep
> > > 3. Yep. Just clicked on the ISO to start it off, does some fancy stuff of producing an E drive or something, ignore.
> > > 4. It worked !. Think Microsoft just packaged the ISO in old wrapping paper by the name of Windows Server 😉. Contents is W11 22H2. Strange for some people the wrapping paper sticks to the product inside 😐.
> > 
> > 
> > Did the same but it gave an error "Setup has failed to install Windows 11"
> 
> It's weird why it works for some but not for others. I put it down to the way the ISO file is packaged against the local language.
> 
> You could try the DLL trick where you make one of the DLL files a null file, just delete the contents. That's an alternative. You can find that online. Many people use that but ofcourse might be hit by the same issue.
> 
> This method but you open the DLL up in a text editor as save as null. Haven't tried it. Leave the file in place but remove what's in it... preferred to deleting now with this method.
> 
> https://nerdschalk.com/installing-windows-11-on-unsupported-hardware-how-to-remove-appraiserres-dll-to-bypass-requirements-when-using-setup/

Already tried this, still failed...

**Comment by TerryUK** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Yep... that's what I did on Sunday. No issues.
> > > > On 1. Just downloaded the ISO didn't create any bootable.
> > > > 
> > > > 2. Yep
> > > > 3. Yep. Just clicked on the ISO to start it off, does some fancy stuff of producing an E drive or something, ignore.
> > > > 4. It worked !. Think Microsoft just packaged the ISO in old wrapping paper by the name of Windows Server 😉. Contents is W11 22H2. Strange for some people the wrapping paper sticks to the product inside 😐.
> > > 
> > > 
> > > Did the same but it gave an error "Setup has failed to install Windows 11"
> > 
> > 
> > It's weird why it works for some but not for others. I put it down to the way the ISO file is packaged against the local language.
> > You could try the DLL trick where you make one of the DLL files a null file, just delete the contents. That's an alternative. You can find that online. Many people use that but ofcourse might be hit by the same issue.
> > This method but you open the DLL up in a text editor as save as null. Haven't tried it. Leave the file in place but remove what's in it... preferred to deleting now with this method.
> > https://nerdschalk.com/installing-windows-11-on-unsupported-hardware-how-to-remove-appraiserres-dll-to-bypass-requirements-when-using-setup/
> 
> Already tried this, still failed...

It's either your hardware not meeting the spec even with the mods or the ISO, stating the obvious.

**Comment by Aditya-Prakash-YT** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > Yep... that's what I did on Sunday. No issues.
> > > > > On 1. Just downloaded the ISO didn't create any bootable.
> > > > > 
> > > > > 2. Yep
> > > > > 3. Yep. Just clicked on the ISO to start it off, does some fancy stuff of producing an E drive or something, ignore.
> > > > > 4. It worked !. Think Microsoft just packaged the ISO in old wrapping paper by the name of Windows Server 😉. Contents is W11 22H2. Strange for some people the wrapping paper sticks to the product inside 😐.
> > > > 
> > > > 
> > > > Did the same but it gave an error "Setup has failed to install Windows 11"
> > > 
> > > 
> > > It's weird why it works for some but not for others. I put it down to the way the ISO file is packaged against the local language.
> > > You could try the DLL trick where you make one of the DLL files a null file, just delete the contents. That's an alternative. You can find that online. Many people use that but ofcourse might be hit by the same issue.
> > > This method but you open the DLL up in a text editor as save as null. Haven't tried it. Leave the file in place but remove what's in it... preferred to deleting now with this method.
> > > https://nerdschalk.com/installing-windows-11-on-unsupported-hardware-how-to-remove-appraiserres-dll-to-bypass-requirements-when-using-setup/
> > 
> > 
> > Already tried this, still failed...
> 
> It's either your hardware not meeting the spec even with the mods or the ISO, stating the obvious.

May be the Hardware is old,
My specs :

Processor	Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz   3.20 GHz
Installed RAM	8.00 GB
System type	64-bit operating system, x64-based processor

but Win 11 21h2 works fine.....

**Comment by TerryUK** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > Yep... that's what I did on Sunday. No issues.
> > > > > > On 1. Just downloaded the ISO didn't create any bootable.
> > > > > > 
> > > > > > 2. Yep
> > > > > > 3. Yep. Just clicked on the ISO to start it off, does some fancy stuff of producing an E drive or something, ignore.
> > > > > > 4. It worked !. Think Microsoft just packaged the ISO in old wrapping paper by the name of Windows Server 😉. Contents is W11 22H2. Strange for some people the wrapping paper sticks to the product inside 😐.
> > > > > 
> > > > > 
> > > > > Did the same but it gave an error "Setup has failed to install Windows 11"
> > > > 
> > > > 
> > > > It's weird why it works for some but not for others. I put it down to the way the ISO file is packaged against the local language.
> > > > You could try the DLL trick where you make one of the DLL files a null file, just delete the contents. That's an alternative. You can find that online. Many people use that but ofcourse might be hit by the same issue.
> > > > This method but you open the DLL up in a text editor as save as null. Haven't tried it. Leave the file in place but remove what's in it... preferred to deleting now with this method.
> > > > https://nerdschalk.com/installing-windows-11-on-unsupported-hardware-how-to-remove-appraiserres-dll-to-bypass-requirements-when-using-setup/
> > > 
> > > 
> > > Already tried this, still failed...
> > 
> > 
> > It's either your hardware not meeting the spec even with the mods or the ISO, stating the obvious.
> 
> May be the Hardware is old, My specs :
> 
> Processor Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz 3.20 GHz Installed RAM 8.00 GB System type 64-bit operating system, x64-based processor
> 
> but Win 11 21h2 works fine.....

Mines 

Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz   3.30 GHz

& 8GB.

Evo SSD.

I wouldn't give up hope yet. Think there is talk of a new ISO.
