### ISSUE TITLE
update existing win 11 to 22h2

### ISSUE THREAD

**Issue by xJustDoNothing** [AveYo/MediaCreationTool.bat#202]
Is there a way to use this tool to update win 11 to 22h2 on unsupported hardware? 
My windows updater seems to have a problem and can't install new updates anymore and now i wondered if I could use this tool to manually update my windows version.
ps: I would like to keep my apps settings and files.

**Comment by AveYo** [comment]
Not yet supported. Come back tomorrow, I might add support for it by then.

**Comment by Aditya-Prakash-YT** [comment]
> Not yet supported. Come back tomorrow, I might add support for it by then.

It's been 11 hours.....

**Comment by xJustDoNothing** [comment]
> Not yet supported. Come back tomorrow, I might add support for it by then.

Thanks for your fast answer :) I've kinda managed to do it right now with a lil tweaking. And to the other guy I'm not impatient I just tried to find a way to fix my windows and this was kinda a promising way to try to fix it without making a fresh Install.

**Comment by Aditya-Prakash-YT** [comment]
> > > Not yet supported. Come back tomorrow, I might add support for it by then.
> > 
> > 
> > It's been 11 hours.....
> 
> i'm shocked to see how people talk...their impatience...do you ever think the developer has a life and is doing this for free! to please people like you who are embittered! You should be ashamed but I'm sure you don't mind. in short personally I thank the work that all these developers do without expecting anything from us. at least some respect. thank you.

Sorry, My Bad but I didn't mean that,.....
Even I am a developer and I also know the presure, I was just kidding there, sorry for my mistake

**Comment by d1stru3t0r** [comment]
> > > Not yet supported. Come back tomorrow, I might add support for it by then.
> > 
> > 
> > It's been 11 hours.....
> 
> i'm shocked to see how people talk...their impatience...do you ever think the developer has a life and is doing this for free! to please people like you who are embittered! You should be ashamed but I'm sure you don't mind. in short personally I thank the work that all these developers do without expecting anything from us. at least some respect. thank you.

He also said tomorrow 14 days ago, maybe that's why the user was reminding him about what he said. Not talking about AveYo specifically, but if you get an ETA about something, or an aprox. then stick to it, otherwise the users will have problems. At least they still got what they wanted.

**Comment by tefracky** [comment]
> > He also said tomorrow 14 days ago, maybe that's why the user was reminding him about what he said. Not talking about AveYo specifically, but if you get an ETA about something, or an aprox. then stick to it, otherwise the users will have problems. At least they still got what they wanted.
> 
> _**"probably"**_ vs. "definitely" _**"might"**_ vs. "will"
> 
> It is not my intention to break people's feathers / flows / whatever. Stuff happens. Like doing a stand-alone powershell snippet for esd parsing/extracting/updating and hitting a road-block at 90% done. I just could not give up on it after investing so much time, and yet here I am, about to give up on it. Who cares? Well, some might when they see an external dependency on wimlib.

Don't give up, I'm sure you'll manage somehow! And to be honest it would be nice to update Windows 11 to 22H2 but it's also nice to have Windows 11 at all and that's what I've achieved with your tool, thanks a lot!
