### ISSUE TITLE
Skip_TPM_Check_on_Dynamic_Update.cmd not working

### ISSUE THREAD

**Issue by KaiAntares** [AveYo/MediaCreationTool.bat#206]
Greetings, first of all forgive my English... The problem is that after applying the mentioned Script, the lack of TPM and Secure Boot to update to Windows version 22h2 continues to appear.
I have 21h2 and already at the time I had to do a clean installation from W10 to W11 for the same reason.  Unfortunately, the Script never worked for me or any of the other possible ways.  It always comes out that my equipment is not compatible.

**Comment by kleuter** [comment]
+1
