### ISSUE TITLE
Password problem

### ISSUE THREAD

**Issue by Clementy01** [AveYo/MediaCreationTool.bat#207]
I recently installed windows 11 with media creation tool.bat and I have a big problem, after the complete installation of the software, it logged me in and says "other user" and asks me to enter my name and password, I tried dozens of passwords. and I don't go, what should I do? please help

**Comment by JonnyTech** [comment]
There should be a list of users on the login screen. Select your correct user from there. Or type your username manually.

**Comment by Vanish14** [comment]
I have the same problem!!
