### ISSUE TITLE
Windows 10 22h2 is out now but unsupported by the script

### ISSUE THREAD

**Issue by 0n** [AveYo/MediaCreationTool.bat#210]
please fix

**Comment by AT-StephenDetomasi** [comment]
It is being worked on, shouldn't be too much longer.

**Comment by DAcKeyy** [comment]
> great job! thanks a lot..... I forgot my bios' password and can't enable TPM haha...

Do you mean if I enable TPM on my machine I can get version 22H2?

**Comment by reoLantern** [comment]
> machine

yes, win11 requires TPM 2.0 turned on

**Comment by reoLantern** [comment]
> > great job! thanks a lot..... I forgot my bios' password and can't enable TPM haha...
> 
> Do you mean if I enable TPM on my machine I can get version 22H2?
yes, win11 requires TPM 2.0 turned on

**Comment by reoLantern** [comment]
> > great job! thanks a lot..... I forgot my bios' password and can't enable TPM haha...
> 
> Do you mean if I enable TPM on my machine I can get version 22H2?

yes, win11 requires TPM 2.0 turned on

**Comment by DAcKeyy** [comment]
> > > great job! thanks a lot..... I forgot my bios' password and can't enable TPM haha...
> > 
> > 
> > Do you mean if I enable TPM on my machine I can get version 22H2?
> 
> yes, win11 requires TPM 2.0 turned on

Checked this tpm.msc, I have a TPM v2 on my PC, but I still don't see any 2H22 Win10.iso download option.

**Comment by jimison** [comment]
According to the current MCT and ISO downloads, looks like the new "choice" for Win 10 22H2 should be as follows: 
`:choice-14 ::# move old choice-14 to choice-15
set "VER=19045" & set "VID=22H2" & set "CB=19045.2006.220908-0225.22h2_release_svc_refresh" & set "CT=2022/10/" & set "CC=1.4.1"
::# set CAB goes here
set "EXE=https://download.microsoft.com/download/9/e/a/9eac306f-d134-4609-9c58-35d1638c2363/MediaCreationTool22H2.exe"
goto process ::# refreshed 19041 base with integrated 22H2 enablement package - current`

as well as the increased Version choice count:
`::# MCT Version choice dialog items and default-index [11]
set VERSIONS=1507,1511,1607,1703,1709,1803,1809,1903,1909,20H1,20H2,21H1,21H2,22H2,11
set /a dV=15`

Not sure what to set set CT and CC to, nor the CAB url. Assume CT is 2022/10/ as 22H2 started rolling out in October. I also don't know what CC represents. If that's found as well as the CAB, the update to the bat should be good to go.

**Comment by davidenco** [comment]
Any update on the Windows 10 22H2 support?

**Comment by WinSSitaly** [comment]
where is cab link of win10 22h2 ?
