### ISSUE TITLE
Can't make a ISO for W10 22H2?

### ISSUE THREAD

**Issue by CG5isthebest** [AveYo/MediaCreationTool.bat#212]
It doesn't show me the option for Windows 10 22H2.

**Comment by james28909** [comment]
how can we add windows 10 22h2?

**Comment by nondetect** [comment]
> It doesn't show me the option for Windows 10 22H2.

> how can we add windows 10 22h2?
> 
> could someone elaborate on this? i also do not know how to make a windows 10 22h2 iso or installable media

Use community [Pull Request ](https://github.com/AveYo/MediaCreationTool.bat/blob/157ed8df1d73b090712f151c774063224890416c/MediaCreationTool.bat)  were is 22h2 is added

**Comment by CG5isthebest** [comment]
who still remembers this post lol got a w11 pc
