### ISSUE TITLE
We need Windows 11 22H2 version supported!

### ISSUE THREAD

**Issue by Markellas** [AveYo/MediaCreationTool.bat#217]
**Please add support for building an ISO image with bypassing the minimum system requirements with Windows 11 version 22H2!**

We really need it!

**Comment by tet666** [comment]
Well it's been a while so the dev is probably busy with other stuff, just use [https://rufus.ie/en/](Rufus) instead it's easy enough to use and can do that and much more.

**Comment by Markellas** [comment]
> Well it's been a while so the dev is probably busy with other stuff, honestly just use [Rufus](https://rufus.ie/en/) instead it's easy enough to use and can do that and much more.

Well, Rufus is good if you need to install Windows 11 22H2 right from a flash drive to some device.

But I need only an ISO image with bypass restrictions.

P.S.: I already found a way to create such an ISO image with MSMG Toolkit, which is basically what I used to build Windows 11.

But it would be nice if this tool could do that too :)

**Comment by Tiger-AC** [comment]
Just run [Skip_TPM_Check_on_Dynamic_Update.cmd](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd) and then the latest standard win11.iso file from Microsoft Windows 11 download site: You don't need modifying anything.

**Comment by githubethansmith** [comment]
It tries to install Server edition (I have Xeon laptop)On Nov 27, 2022, at 7:04 PM, Tiger-AC ***@***.***> wrote:﻿
Just run Skip_TPM_Check_on_Dynamic_Update.cmd and then the latest standard win11.iso file from Microsoft Windows 11 download site: You don't need modifying anything.

**Comment by Tiger-AC** [comment]
Yes, I am also using Xeon CPU and the downloaded standard win11.iso showing it is Server edition during the installation. But once installed, it is actually the normal home version.

**Comment by JonnyTech** [comment]
> It tries to install Server edition

It is a well known issue that Microsoft packaged the Windows 11 installer incorrectly. Ignore the wording, Windows 11 will be installed.

**Comment by jac1945** [comment]
Bonjour, j'ai tout essayé rien à faire. La version Win11 21H2 s'installe sans problème. La 22H2 que ce soit en mise à jour u installation complète rien à faire blocage vers 11% sans message d'erreur.
MàJ faite en lançant d'abord Skip_TPM_Check_on_Dynamic_Update.cmd et en copiant dans le répertoire source le fichier appraiserres.dll ......... blocage
Installation complète avec Rufus après avoir mis le fichier appraiserres.dll, pareil.
Et pourtant la version 21H2 marche très bien.

**Comment by VanChapel** [comment]
![image](https://github.com/AveYo/MediaCreationTool.bat/assets/31875552/bed0a7aa-1786-4d53-9479-4000dacf988b)
that is the message I receive

**Comment by VanChapel** [comment]
anyone will fix this?  the Scripts is not working lately

**Comment by ElliotKillick** [comment]
If you're okay with WSL then I've just made a similar project called Mido: https://github.com/ElliotKillick/Mido

It's minimalist in that it's only for downloading the ISOs. Very clean and readable shell script. :)

Just an alternative for those who want something a bit simpler for VMs and such. Doesn't replace this **amazing** project in any way. ❤️
