### ISSUE TITLE
Should i delete these files created by this tool?

### ISSUE THREAD

**Issue by shanmugad** [AveYo/MediaCreationTool.bat#229]
Screenshot 

![image](https://user-images.githubusercontent.com/121617479/209983146-955fe7bf-3014-421a-b2ec-b27bf9db8048.png)

**Comment by AveYo** [comment]
Can delete `ESD` and `$Windows.~WS` without any issues
`PerfLogs` is done by windows (telemetry, so also ok)
`$WinREAgent` should be left alone, it's managed by windows for recovery environment purposes
