### ISSUE TITLE
Update to win 11 MediaCreationTool11.exe download failed

### ISSUE THREAD

**Issue by mrranger** [AveYo/MediaCreationTool.bat#242]
![Screenshot_27](https://user-images.githubusercontent.com/13420378/216546160-a0deec7a-0445-48c3-ad85-bac85401b408.png)

**Comment by F11enDy** [comment]
I have this problem too, what me to do?

**Comment by kristaliksVIP** [comment]
Такая же!

**Comment by nondetect** [comment]
> Такая же!

if you located in RU use vpn to use this tool, access to Microsoft servers from RU is blocked

**Comment by NuriG** [comment]
Пробовал с VPN все равно не работает! Блин, в чем может быть дело, никто не решал такую проблему?

**Comment by ZeroGit2015** [comment]
1) Download MediaCreationTool11.exe from Internet archive (this file was deleted on Microsoft servers, but you can find it on Web Archive Sites). 
2) Run Mediacreationtool.bat (You will get error).
3) Put MediaCreationTool11.exe to C:\ESD\MCT (IMPORTANT: please check filename register))
4) Run Mediacreationtool.bat again
