### ISSUE TITLE
How to uninstall Skip_TPM_Check_on_Dynamic_Update.cmd ?

### ISSUE THREAD

**Issue by mdio33** [AveYo/MediaCreationTool.bat#243]
Hello.

I've tryed the script on a macbook pro late 2014 on boot camp and after a long time waiting, the setup reverted to windows 10

Now i want to uninstall everything that Skip_TPM_Check_on_Dynamic_Update.cmd  changed, but everytime I run it I get the message....

` Skip TPM Check on Dynamic Update V10  INSTALLED  run again to remove`

But it does not change anything... how to uninstall ??

Thanks.

**Comment by nondetect** [comment]
Try to use run command "remove", in cmd from admin type: 
> .\Skip_TPM_Check_on_Dynamic_Update.cmd remove

**Comment by adukugideon** [comment]
Tried @nondetect's method. Does not work

**Comment by AveYo** [comment]
Something is wrong in your environment. You don't have proper admin rights most likely.

The minimal undo is to delete from the registry:
`HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SetupHost.exe`
