### ISSUE TITLE
This PC can't run Windows 11

### ISSUE THREAD

**Issue by adistaxtos** [AveYo/MediaCreationTool.bat#244]
When i try to clean install win 11 on my pc after i choose the version of windows i get this error. [https://prnt.sc/dWTPgKSY66W4](url)
My pc is meets all the system requirements and i have test the pc health app and says my pc is ok.
I have upgraded to windows 11 through upgrade and i am running the with no issue but i can't do a clean install.
Any solutions?

**Comment by nondetect** [comment]
It is very difficult to advise you, because you did not provide any information about your PC, the most common error during a clean installation is incorrect disk type (MBR instead of GPT), you can check it in _diskpart_ or any 3-party disk program, and if it's MBR change it to GPT

**Comment by pacav69** [comment]
i suggest trying using this app from MS this will display any problems.
[Windows 11 Installation Assistant](https://www.microsoft.com/en-au/software-download/windows11/)

**Comment by adistaxtos** [comment]
I just clean installed windows 10 and then upgraded to windows 11 right after
