### ISSUE TITLE
Error when upgrading to windows 11

### ISSUE THREAD

**Issue by kristaliksVIP** [AveYo/MediaCreationTool.bat#247]
![216546160-a0deec7a-0445-48c3-ad85-bac85401b408](https://user-images.githubusercontent.com/125814861/219957845-f498afe8-c0ee-4a06-be07-5a2c849f688b.png)

**Comment by nondetect** [comment]
if you located in RU use vpn to use this tool, access to Microsoft server from RU is blocked
