### ISSUE TITLE
Issue upgrading from Win10 to 11

### ISSUE THREAD

**Issue by luanfsp** [AveYo/MediaCreationTool.bat#248]
Give this message.

Previously running Win7
Updated to Win10 without data loss
converted to gpt and made it EFI

Now a getting the error to update to Win11 without data loss.

![Anotação 2023-02-19 194336](https://user-images.githubusercontent.com/31630621/219979782-5aea6bd0-7d52-4382-b225-6313f8c906a3.png)

Translated: Sorry, We're having problems to determine if your pc can execute Windows 11. Close the installation and try again.

**Comment by tedztar** [comment]
This looks like an issue with your computer not being capable running windows 11 not an issue with the tool.
Id suggest getting the windows 10 health check app as this will tell you if you computer is compatible with windows 11.
If it is not compatible with windows 11 as far as I am aware you will need to do a fresh reinstall to get it.

**Comment by luanfsp** [comment]
Thanks
