### ISSUE TITLE
Windows 11 22H2 Unsupported

### ISSUE THREAD

**Issue by joesixpack** [AveYo/MediaCreationTool.bat#260]
Title says it all.

**Comment by nondetect** [comment]
Author is no longer here, you can use [this Pull Request](https://github.com/AveYo/MediaCreationTool.bat/pull/230) 




Gh

**Comment by tarvcode** [comment]
For those finding this, the updated code does work, but 22h2 was updated in September that will not bypass the hardware checks.   To upgrade from 21h2, you need to find an older ISO.  I just used one from Dec 2022 and it worked.
