### ISSUE TITLE
[Crash] Media Setup Host

### ISSUE THREAD

**Issue by mdstoll** [AveYo/MediaCreationTool.bat#265]
I get a message that Media Setup Host crashed after trying to run the upgrade.
Any suggestions on how to prevent this? Anyone else seen this issue?

**Comment by pacav69** [comment]
I would recommend to backup your personal files and do a fresh/clean install.

**Comment by mdstoll** [comment]
I ended up solving this the following way. What needs to be noted for future reference is that I was upgrading from an old Enterprise edition of windows 10.

First, I edited the MediaCreationTool.bat file to set the version to 'professional'. I also enrolled in Windows Insider Preview Channel. With the MediaCreationTool I managed to push windows to Windows 10 version 1507. This changed the version from Enterprise to Pro. After that I was able to do an update to 11_22H2 as per this pull request https://github.com/AveYo/MediaCreationTool.bat/pull/230 which worked flawlessly.
