### ISSUE TITLE
Programme fails to complete

### ISSUE THREAD

**Issue by AreJayAreEm** [AveYo/MediaCreationTool.bat#28]
When launching the .bat file, the programme gets to about here and then I get a message pop up on the screen.
![image](https://user-images.githubusercontent.com/93429244/139529194-ca69f577-6d7d-489a-94e7-d64989a7f003.png)
The .bat file screen then disappears and does not return.

![image](https://user-images.githubusercontent.com/93429244/139529218-6f82d4f0-8cd3-4e4c-841b-96f6daba0b17.png)
Whatever button I click on the pop-up, the pop-up disappears but nothing else happens.

I've deleted all the files I can find related to this tool and downloaded a fresh copy but the same thing happens so I must be missing something.

The first time I ran this tool I got past this stage and was able to select Windows 11 and then the Create ISO option but it got to a point and then stopped. Unfortunately I didn't take a screenshot.
When it stopped the first time around, I got a pop-up from my anti-virus software so I think it might have done something but cannot be certain. Do you have any ideas on how to fix this?

Appreciate your time and effort in producing this tool.

**Comment by AreJayAreEm** [comment]
I've extracted the files from the zip archive onto my desktop and have tried running the .bat file again. Now the programme runs to here but then the window closes. I do not get the message about putting files in an archive any more.
![image](https://user-images.githubusercontent.com/93429244/139538148-16dfdcdc-c54b-4478-bfaf-b35550fe72ae.png)

**Comment by AveYo** [comment]
is this still an issue with the last update?

**Comment by AreJayAreEm** [comment]
Hi, to be honest I haven't tried it again as I used Hyper-V in the end. You can toggle the TPM directly in the settings there.
