### ISSUE TITLE
Doesn't work on Build 25977

### ISSUE THREAD

**Issue by Soberia** [AveYo/MediaCreationTool.bat#286]
I used `Skip_TPM_Check_on_Dynamic_Update.cmd` to bypass the TPM check on installing build 25967 and it worked just great, but after running the script to install build 25977, I got the following error when tried to update directly:
![image](https://github.com/AveYo/MediaCreationTool.bat/assets/30440494/f94f0b18-7736-440a-924f-4723124035c9)

I also tried with the ISO file but `setup.exe` did not open at all when the script was enabled.

If I disable the `Skip_TPM_Check_on_Dynamic_Update.cmd` script and run `auto.cmd`, I will get this:
![image](https://github.com/AveYo/MediaCreationTool.bat/assets/30440494/3ab5a290-da13-408a-870e-f44350fd32dc)

**Comment by nondetect** [comment]
Reapply script and check folder where script file stores - C:\Scripts\get11.cmd
Maybe AV is delete it

**Comment by Soberia** [comment]
It seems it's resolved in build 25982. I close this now.
