### ISSUE TITLE
upgrading fails on the restart screen 21h2 to 22h2

### ISSUE THREAD

**Issue by diosscuri** [AveYo/MediaCreationTool.bat#287]
firstly I find suspicious and doubt on the success of the install from the start when activating the script it bypasses the TPM 2.0 and Secure Boot section but still stays as Windows 11 on the installer and not as Windows Server and secondly running past this process on the restart page it fails on a Blue Screen under the stop code DRIVER_IRQL_NOT_LESS_OR_EQUAL with rt640x64.sys failing.
I have tried getting the rt640x64.sys driver because to my surprise when checking I did not even have it in my system so I installed it and no success still but another suspicious thing is that while on MediaCreationTool.bat the System doesn't even detect as Windows 11. I have also tried downloading an old version of the 22h2 installer to no success also...

![issue2h22github](https://github.com/AveYo/MediaCreationTool.bat/assets/148577084/8e4d91f1-d540-4d18-a63c-7d174602024f)

**Comment by nondetect** [comment]
BSoD tells you that the problem with your Realtek driver/device - built-in Ethernet or Sound device on motherboard usually. It's common problem on Insider builds with unsupported hardware appears time to time between build.
Try to use Windows default driver for this device and unplug cables and Disable device in Device Manager before update restart begins

**Comment by diosscuri** [comment]
could you elaborate more on how to find the default, manufactured drivers and for which devices? (worth noting that i came to windows 11 from a windows 7 manufactured operating system and i tried on the CD of the drives it wouldn't work for this OS, it rejected immediately.)

![devmnggithub](https://github.com/AveYo/MediaCreationTool.bat/assets/148577084/640a0994-5333-46d4-9298-1d040bcd07d6)

**Comment by diosscuri** [comment]
searching on C:\Windows\System32\drivers for rt640x64.sys shows that it isn't installed or available.

![rt640x64 sysgithub](https://github.com/AveYo/MediaCreationTool.bat/assets/148577084/887ae350-cbf8-4273-9123-ce559ea31e59)

**Comment by nondetect** [comment]
After Windows Update requires Restart go to Device manager and disable "Realtek PCIe GbE Family Controller", unplug internet cable and then Restart with update.

**Comment by diosscuri** [comment]
it doesn't show this that Windows Update requires Restart it instead takes the whole screen on a blue background Installing Windows 11

![4phases22h2](https://github.com/AveYo/MediaCreationTool.bat/assets/148577084/81949706-844a-4687-8b55-2a95c4bd5b7a)

**Comment by diosscuri** [comment]
I was able to upgrade to 22h2 disabling the Realtek PCIe GbE Family Controller and disconnecting the internet cable and now after plugging the cable again it restarted into a Blue Screen with DPC Watchdog Violation I am going through it now

**Comment by diosscuri** [comment]
issue fixed after downloading and using my phone to transfer the latest realtek driver installer to the pc while it had the internet cable unplugged and driver disabled and now it's installing updates all is smoother and better! thank you @nondetect for the beautiful help! i am grateful for everything! I LOVE YOU! thank you @AveYo for the script! I LOVE YOU! Have a beautiful day!
