### ISSUE TITLE
I meant to Selecting as Windows 10 Version 1507 but Why Selected as Version 1607? Random?

### ISSUE THREAD

**Issue by Computer11HX** [AveYo/MediaCreationTool.bat#30]
Check out... There's a Issues?
![image](https://user-images.githubusercontent.com/88474411/140041589-62f44bd8-4b10-458d-9f52-804311e79623.png)

**Comment by AveYo** [comment]
Yes, I believe something broke along the way for old versions. Should be fine after today's update
