### ISSUE TITLE
Cannot find Windows 10 LTSB/LTSC versions

### ISSUE THREAD

**Issue by Abhishek-675** [AveYo/MediaCreationTool.bat#300]
Where can I find windows 10 1607 LTSB version?

**Comment by JonnyTech** [comment]
https://tb.rg-adguard.net/dump.php?seach=1607%20enterprise%20vl

**Comment by Abhishek-675** [comment]
![2023-12-02 20_06_50-](https://github.com/AveYo/MediaCreationTool.bat/assets/94445399/78a13e91-c2a6-4318-a0a5-b5fc09b6b1f9)
This above link contains normal enterprise, not the LTSB version. Thanks anyway.

**Comment by JonnyTech** [comment]
https://files.rg-adguard.net/search >> search >> `2016_ltsb` (including the underscore)
