### ISSUE TITLE
Malware Detected

### ISSUE THREAD

**Issue by jerick70** [AveYo/MediaCreationTool.bat#309]
Hi I'm using your latest Skip_TPM_Check_on_Dynamic_Update.cmd file (https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd).

When I run the .cmd file I'm getting a malware detection pop-up from Sophos for 'Exec_12a (T1059.001)' malicious behavior detected in 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'.  Then the process C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe is terminated by Sophos.

You will want to put a request in with Sophos to rectify this.

**Comment by AveYo** [comment]
If they can't whitelist such a simple script fitting a single screen page, they are not a good AV.
Please do make a report yourself since you're a customer.

**Comment by jerick70** [comment]
Yes, I've entered a case for this.  My company is a business subscriber with Sophos.  We will get this whitelisted.
