### ISSUE TITLE
Please add windows 7 download link

### ISSUE THREAD

**Issue by raunaksingh765** [AveYo/MediaCreationTool.bat#322]
hello sir i am requesting you to pls add windows 7 download links its a humble request with you.

**Comment by nondetect** [comment]
Windows 7 is no longer available to download for users since 2020 (maybe it's still available for MSDN subscriber by paid subscription, but it's not public link), and till this tool only used download link from MS servers it's not possible to add Windows 7.

You can download Windows 7 in some languages from this [archive org](https://archive.org/download/digital_river)(edition/language described in file [xxx17index_file.txt](https://archive.org/download/digital_river/xxx17index_file.txt)), but I can't guarantee its original ISO 

Hope I answer your question and you can close the "Issue/Request".

**Comment by raunaksingh765** [comment]
thanks bro

**Comment by mrfoxesite** [comment]
stupid indians using windows 7. indians are really dumb tho

**Comment by raunaksingh765** [comment]
> pid indians using windows 7. indians are really dumb

give us new pc wen

**Comment by mrfoxesite** [comment]
windows 7 to 10 is easy and free (atleast before) you can install windows 10 1909 without internet to still get free upgrade if 22h2 doesn't work and then upgrade later on. windows 10 licenses are dirt cheap.

**Comment by raunaksingh765** [comment]
> also they lack in decent english

bro i think you don,t use telegram i need windows 7 because many schools in india have low  end computers and windows 7 easily run on low end pc

**Comment by mrfoxesite** [comment]
windows 7 to 10 is simple make sure you max out the RAM and have SSD also free upgrade is over so upgrade to [windows 10 1909(english, x64)](https://archive.org/details/Win10_1909_English_x64) then open microsoft store and then update all apps, then update to 22h2 using windows update and its that simple.

**Comment by mrfoxesite** [comment]
> > also they lack in decent english
> 
> bro i think you don,t use telegram i need windows 7 because many schools in india have low end computers and windows 7 easily run on low end pc

i know but windows 7 is really outdated for daily use and Tiny10 or Tiny11 is better. the best to try is linux

**Comment by mrfoxesite** [comment]
you could also build your own windows 10 iso too.

**Comment by mrfoxesite** [comment]
> 
> bro i think you don,t use telegram i need windows 7 because many schools in india have low end computers and windows 7 easily run on low end pc
linux is more lightweight and runs faster on low end pcs. linux mint is great distro for windows users!

**Comment by raunaksingh765** [comment]
> you could also build your own windows 10 iso too.

yeah i know bro thanks for telling me

**Comment by Infraction7** [comment]
leave out of windows 7

**Comment by mrfoxesite** [comment]
> leave out of windows 7

true

**Comment by mrfoxesite** [comment]
> > you could also build your own windows 10 iso too.
> 
> yeah i know bro thanks for telling me

use NTLite or chris titus tech debloat scripts
