### ISSUE TITLE
Language selection needed

### ISSUE THREAD

**Issue by jejvilen** [AveYo/MediaCreationTool.bat#325]
Mediacreationtool.bat: The automation is kind of nice - or actually not. I really would like to get different language downloaded but it is not possible. It only downloads the language the Windows you are running the script in uses.

**Comment by nondetect** [comment]
If you choose "Select" or "MCT defaults" option in start menu, not "Auto..." ones
![image](https://github.com/AveYo/MediaCreationTool.bat/assets/14868034/c98486ea-162b-4058-8121-6349f107e653)

you will have option to choose what language/edition download in program like default MediaCreationTool does
![image](https://github.com/AveYo/MediaCreationTool.bat/assets/14868034/0ee93d73-7ea2-45d6-9816-52e64556cf96)


Hope I help answer your question/request and you can close this Issues

**Comment by jejvilen** [comment]
Thank you, how did I ever miss that?

**Comment by mrfoxesite** [comment]
Could you fix my issue sir? https://github.com/AveYo/MediaCreationTool.bat/issues/324

**Comment by gmy77** [comment]
> Hope I help answer your question/request and you can close this Issues.

Fantastic, thanks, and above all, this is the ULTIMATE, COMPLETE tool of this type, work PERFECTLY. I say thanks one thousand times.
