### ISSUE TITLE
Help!! Error

### ISSUE THREAD

**Issue by fabmm** [AveYo/MediaCreationTool.bat#33]
After the download for windows 11 is complete, it goes into a blue screen to install, then the PC restarts. it reaches 30s, then it restarts again, then it reaches 40s then the whole PC shuts down fully!!
After I boot manually, I get this error from windows upgrade 
"we couldn't install windows 11 0xc1900101 - 0x30018"

Before i raised an issue, i tried everything on this page to make sure i tried my best.
https://softwaretested.com/windows/windows-10-error-code-0xc1900101-0x30018/

Please guide me

**Comment by AveYo** [comment]
try to setup 10 instead first - doing an in-place upgrade, it should fix many issues
then try 11 setup again (should rename script as `no_update MediaCreationTool.bat` for troubleshooting)

**Comment by fabmm** [comment]
I did that and it worked! Thank you! I can't believe 3 days of researching on Google got me nowhere.
Have a great day
