### ISSUE TITLE
Not Work. Error.

### ISSUE THREAD

**Issue by MiraMaX166** [AveYo/MediaCreationTool.bat#337]
![image](https://github.com/AveYo/MediaCreationTool.bat/assets/16999454/f32986ae-dea2-43ab-b3ce-4c95b54154ec)

**Comment by makehillflat** [comment]
Same thing here. For the last 10 hours

**Comment by JonasGMorsch** [comment]
Hi, I found the problem on w10 22h2:
the following line (166) is not downloading correctly anymore:
``
set "EXE=https://download.microsoft.com/download/9/e/a/9eac306f-d134-4609-9c58-35d1638c2363/MediaCreationTool22H2.exe"
``
now it needs to be:

``
set "EXE=https://download.microsoft.com/download/9/e/a/9eac306f-d134-4609-9c58-35d1638c2363/MediaCreationTool_22H2.exe"
``

EDIT:
It is also needed to clean files at "C:\ESD" for the script to download the correct file

EDIT 2:
Just made a pull request with the new filename

**Comment by Kendeue** [comment]
1, Replace this.
`set "EXE=https://download.microsoft.com/download/9/e/a/9eac306f-d134-4609-9c58-35d1638c2363/MediaCreationTool22H2.exe"`

with this
`set "EXE=https://download.microsoft.com/download/9/e/a/9eac306f-d134-4609-9c58-35d1638c2363/MediaCreationTool_22H2.exe"`

2. Delete C:\ESD

4. Run the bat again and it works

![image](https://github.com/AveYo/MediaCreationTool.bat/assets/104274248/2262060e-de05-42db-b121-fe0a471e7adc)

**Comment by MiraMaX166** [comment]
Thank you very much friends, but I already installed Linux)

**Comment by ImMALWARE** [comment]
Is this only for 22H2? Or are there any other versions with name changed?
