### ISSUE TITLE
[Feature Request] Add to select mode without tpm in download iso or with tpm 2.0 with secure boot

### ISSUE THREAD

**Issue by evghenii12** [AveYo/MediaCreationTool.bat#35]
Add to select mode without tpm in download iso or with tpm 2.0 with secure boot

**Comment by AveYo** [comment]
You can already do that by selecting `Default MCT` choice = without tpm bypass
All others choices should include tpm bypass

You can also rename the script as "_**def** MediaCreationTool.bat_" to force only default media

So I'm not sure if yet another choice would fit
