### ISSUE TITLE
Selected auto install, upgrading to windows server instead of 11

### ISSUE THREAD

**Issue by AcTiViSioN911** [AveYo/MediaCreationTool.bat#36]
Hello.  I have already updated 2 computers with this method.  But my third computer is on a xeon processor and when I updated win 10 home I saw the title Installing Windows Server ... now updating and I hope it's just a mistake in the title.

**Comment by e-t-l** [comment]
@AcTiViSioN911 So what happened? Did it actually install Win 11 or something else?

**Comment by AcTiViSioN911** [comment]
> @AcTiViSioN911 So what happened? Did it actually install Win 11 or something else?

Forgot to answer, Windows 11 Home was installed.  It's strange that the title was about the server.

**Comment by e-t-l** [comment]
Good to hear. 

From the dev's comment on https://github.com/AveYo/MediaCreationTool.bat/issues/19#issuecomment-962656402
> the cosmetic Installing Windows Server..

It would appear that this is, like you said, just a cosmetic mistake in the title that they're working on correcting.

**Comment by e-t-l** [comment]
[Recommend ckosing this issue]

**Comment by AveYo** [comment]
Just for the sake of form over function, I have switched away from /Product Server bypass
So now you get the Windows 11 label back ;)
It also works for setup.exe, you don't have to use auto.cmd for it to be active
