### ISSUE TITLE
Location of new Windows 11 ISO File?

### ISSUE THREAD

**Issue by LeeWeiZhong** [AveYo/MediaCreationTool.bat#37]
Unable to determine location of new Windows 11 ISO file after windows installation media is finished.

**Comment by AveYo** [comment]
defaults to your Downloads directory - for the automated one-click choice

**Comment by rbreaves** [comment]
Be that as it may it flashes by really quickly and gives the users no chance of knowing. It would be more predictable to put it in the path of app itself, but instead I am now having to run through this twice.

**Comment by AveYo** [comment]
It is also written in the script output, tho. It's only minimized while processing - maybe I should stop doing that.

**Comment by rbreaves** [comment]
Yea, I think the script simply crashed earlier for some weird reason - after the second run it did indeed give me useful output on its destination. Thank you for this amazing script!
