### ISSUE TITLE
cant download windows 10 1607

### ISSUE THREAD

**Issue by BattouKen** [AveYo/MediaCreationTool.bat#371]
cant download windows 10 1607

![image](https://github.com/user-attachments/assets/053bd2fa-8a5f-465c-97e4-db72770e06a1)

**Comment by JonnyTech** [comment]
Microsoft no longer supply **previous** builds of Windows to download. Only the **current** release of Windows 10 and 11 are available from their servers.

**Comment by LightYagami28** [comment]
@BattouKen Close this issues pls

**Comment by BattouKen** [comment]
> @BattouKen Close this issues pls

why?

porque? yo creo que si puede tener arreglo, hay ISO's de la 1607 sin tocar y sin malwhare en la web de archive.org por ejemplo (https://archive.org/details/win10-1607) ahí esta un iso version pro y home.

**Comment by nondetect** [comment]
> > @BattouKen Close this issues pls
> 
> why?
> 
> porque? yo creo que si puede tener arreglo, hay ISO's de la 1607 sin tocar y sin malwhare en la web de archive.org por ejemplo (https://archive.org/details/win10-1607) ahí esta un iso version pro y home.

Because maintainer is absent for a while, and his position is to use only links to MS not side sites. You always can clone repository and make what you want. 
Have a nice day.

**Comment by BattouKen** [comment]
ok, gracias por la info 👍💯
