### ISSUE TITLE
Windows Reports this as a severe threat - Trojan:Win32/Ceprolad.A

### ISSUE THREAD

**Issue by stonking** [AveYo/MediaCreationTool.bat#42]
Windows Reports this as a severe threat.

Trojan:Win32/Ceprolad.A

**Comment by stonking** [comment]
Windows reported this as a severe threat during testing MCT from a fresh Windows 10 install in VMWare.

**Comment by AveYo** [comment]
obviously a false-positive
if you want to help, report it as such to [microsoft](https://www.microsoft.com/en-us/wdsi/filesubmission/)

**Comment by stonking** [comment]
That may be so, but it may also explain some of the other issues people are having if certain steps are being blocked.

**Comment by AveYo** [comment]
The question is what kind of fresh windows 10 install are you testing that fails both the BITS download and the .net framework based one, to reach the 3rd alternative that's only there to help with broken, naked unpatched windows 7.

Anyway, I will remove the certutil based downloader next, I do try helping broken environments but maybe I'm trying too hard.

**Comment by stonking** [comment]
"The question is what kind of fresh windows 10 install are you testing that fails both the BITS download and the .net framework based one, to reach the 3rd alternative that's only there to help with broken, naked unpatched windows 7."

Good question, a "reset" was performed a few days before this test, and it's using a Pro retail key that could be quite old.

Also, the end result of this attempt was a non-working system.

![image](https://user-images.githubusercontent.com/80718664/141519698-d2a939c4-7af3-4a36-9bd7-f86df955643c.png)

**Comment by stonking** [comment]
I have a backup that I'll restore and if there's any info you want me to provide from that install that might help you I can take a look and let you know.

**Comment by AveYo** [comment]
It would be helpful to microsoft but they are not interested in such reports.  
You would get the same failures with the vanilla iso from microsoft
This script can't magically fix the host system

Don't get me wrong, I'm not trying to shift blame here - there's nobody to blame, upgrade process is and always will be unreliable (until microsoft locks everybody to one walled-garden hardware + software configuration like apple or google does)
Tho it should be more reliable for vm's (if you only use non-tweaked images)

Usually what helps is to do a repair-install of the host os, before doing an upgrade, to make sure key components are in good shape (and even that can fail after some destructive tweaks or chopping of the setup image)

I got nothing about that generic error, it's probably a kernel driver
Guess you could run a compatibility report by opening a cmd / powershell in the setup media \ sources, then enter: `setupprep.exe /Compat ScanOnly /Telemetry Disable  /DynamicUpdate Enable /Eula Accept /Product Server`  
Once it reaches the Select what to install / what to keep step, copy the  `C:\$Windows.~BT\Sources\Panther\` folder containing the report, zip it, attach it here and I will take a look at it. Can cancel setup afterwards.

**Comment by stonking** [comment]
> The question is what kind of fresh windows 10 install are you testing that fails both the BITS download and the .net framework based one, to reach the 3rd alternative that's only there to help with broken, naked unpatched windows 7.
> 
> Anyway, I will remove the certutil based downloader next, I do try helping broken environments but maybe I'm trying too hard.

I looked into the history of this VM, the "original edition" key was "Windows 7 Professional Retail" and it was upgraded to Windows 10 from there.

**Comment by AveYo** [comment]
could be, but that's another issue.  
the one at top should be fixed now, since I've removed download via certutil fallback
