### ISSUE TITLE
Bad Link/Missing File

### ISSUE THREAD

**Issue by titan99855** [AveYo/MediaCreationTool.bat#43]
The link in the README.md for Skip_TPM_Check_on_Dynamic_Update v4 gives me a 404. I am guessing it is because this file is not present in the repository.

https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Skip_TPM_Check_on_Dynamic_Update_v4.cmd

**Comment by AveYo** [comment]
updated to point that it's a work-in-progress (hit a blocking issue with it and I'm holding it for now)
