### ISSUE TITLE
Lines 51 & 55 set command not correct

### ISSUE THREAD

**Issue by bigbadmoshe** [AveYo/MediaCreationTool.bat#45]
Original
set/a dV=14
set/a dP=4

Corrected
set /a dV=14
set /a dP=4

I could not get the script to run for me after latest update. So i changed those 2 lines and its working.

Am i correct in that was causing issues?

**Comment by AveYo** [comment]
It should not matter, and it's used everywhere like that - cmd knows how to separate it
While it has burned itself into my style of writing the commands to separate numbers from text, it might confuse others, and as you say, it might even cause issues (in some language / codepage  - unlikely as that may be), so it is worth a shot.
Can you share what's the language for your system?

**Comment by bigbadmoshe** [comment]
Im on Windows 11 English

I used the bat file to upgrade my current Windows 10 to 11 this was before the changes.

I tried it on a clean windows 11 install had the same issues. (it was hebrew os)

the issue for me was after it tries to self elevate. i tried with admin rights as well as not but it keeps on trying to open a new console window.

Hope i am being clear.

**Comment by AveYo** [comment]
That looks more or less corrupted while it refreshed _(that's by design to enforce console style and the path)_,
It could still be the result of copy-paste error or even some av / filter.
Anyway, try the latest, I have done some changes

**Comment by bigbadmoshe** [comment]
I'm going to check if it's a copy paste issue. Will download the files

**Comment by AveYo** [comment]
was it a copy/paste issue, or antivirus filter?

**Comment by bigbadmoshe** [comment]
Everything is working fine with latest version

**Comment by bigbadmoshe** [comment]
Latest version has no issues
