### ISSUE TITLE
Saving ISO Files in C:/ESD

### ISSUE THREAD

**Issue by Arhan2007** [AveYo/MediaCreationTool.bat#46]
@AveYo 
Can you please tell me a way I can make this script use the C:\ESD folder instead of the downloads folder, they way it did earlier. 

I want it to store everything (the MCT Folder, the shortcut to download the latest version of the tool and the ISO File) in the ESD folder.
Thanks.

**Comment by AveYo** [comment]
This last update I have changed it back (sort-of). 
Script will use the folder it is in (and if that's the temp folder means it was run directly from the zip so will fallback to using C:\ESD).
For you that means you just need to copy the script yourself to C:\ESD and run it from there.

**Comment by Arhan2007** [comment]
Ok thanks for helping
