### ISSUE TITLE
Older script to clear TPM keys in Windows 10

### ISSUE THREAD

**Issue by leskgr** [AveYo/MediaCreationTool.bat#47]
Could You be so nice and send me (leskgr@gmail.com) a script written around 5th of Oct 21 to clear all TPM keys. I have an issue with computer (I have WOW6432Node malware) and this helped me to remove some hidden traces (my whole network is infected and this is for another computer). 
There were only 4 or 5 commands that I copied in command prompt and they did the magic (the computer needed restart) and yes thank You in advance, sincerely, Grega Leskovšek from Slovenia

**Comment by AveYo** [comment]
I only shared scripts about Windows 11 TPM bypass, that have nothing to do with the management of an actual TPM device.  
If you do have a TPM device, note that clearing it will result in any encrypted files you have being no longer accessible (if you used Bitlocker Drive Encryption). I suggest giving this a read: https://www.nextofwindows.com/how-to-clear-and-manage-tpm-on-windows-10

**Comment by leskgr** [comment]
Is it possible to upgrade to Windows 11 from 7?
Directly or undirectly?
What is the Windows policy for upgrading from Windows 7 to 10 now? Is it
still possible for free?
Thank You in advance for all the answers and Your help.
Sincerely, Grega Leskovšek from Slovenia

**Comment by AveYo** [comment]
No, upgrading to 11 from 7 with keeping activation and files and programs is blocked. 
So first upgrade to 10. It is still possible for free.
