### ISSUE TITLE
Windows Insider Enrollment and DEF argument

### ISSUE THREAD

**Issue by Arhan2007** [AveYo/MediaCreationTool.bat#48]
@AveYo 
Hello,
I wanted to know how can I use your Win11 Bypass scripts to enroll an unsupported PC in windows insider dev channel. 

and also how do I add the Def argument to the script

**Comment by AveYo** [comment]
See updated readme with a section about insider builds on unsupported hardware  

As for `def` argument, you have many simple choices! Either:
- rename the script from `MediaCreationTool.bat` to `def MediaCreationTool.bat`    
- call the script with arguments from a powershell / cmd prompt: `MediaCreationTool.bat def`  
- edit the script (line 35) from `rem set /a DEF=1` to `set /a DEF=1`   

Note that you could also just use `MCT Defaults` preset - it will create a vanilla, unmodified media
