### ISSUE TITLE
The lastest commit broke the auto setup

### ISSUE THREAD

**Issue by buffos** [AveYo/MediaCreationTool.bat#5]
With the latest commit 1fcb7246620636c9697f10183a1ae446676c4f92 when I select Auto, it will download the iso and prompt me to burn it.

The previous version worked fine.

**Comment by AveYo** [comment]
So automation did not work for you to the fullest, and you had to click Next / Save to proceed.
Not sure I can help with that, but at least I've added back the failsafe to grab whatever iso target is manually selected.

**Comment by buffos** [comment]
>and you had to click Next / Save to proceed.

No. The script ends asking me to burn an ISO to the burner and then ends. It's like I selected to create an ISO (options 2) although I selected AUTO (to install the new version on top).

There is no option to continue and install windows 11.

**Comment by AveYo** [comment]
I meant that it should be automated like this:  
![preview](https://i.imgur.com/3SOp4Ej.gif)  
It's the same for Auto Setup, only that before actually creating an iso, MCT should be terminated, then setup starts (via auto.cmd)

**Comment by AveYo** [comment]
wow, great to provide the actual script output
obviously there's a path separator missing there, no idea how it happened but will sure try to prevent it in the upcoming update for 22000.258

**Comment by AveYo** [comment]
I've migrated to AutoUnattend.xml for tpm reg bypass _(can still force boot.wim override with FIX arg if reg bypass does not work)_   
and revised the whole ui automation logic - It should be a lot more reliable now

**Comment by AveYo** [comment]
closing this since no further input, and default bypass method changed anyway
