### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by titan99855** [AveYo/MediaCreationTool.bat#51]
Windows 11 (Dev Channel) attempted to update (through Windows update) and failed due to it being an unsupported PC. I then ran Skip_TPM_Check_on_Dynamic_Update_v4.cmd, rebooted, and attempted to update again, but the update failed the same way.

To fix the issue, I deleted the $WINDOWS.~BT folder, rebooted, and then tried to update and was successful.

You might consider adding the ability for the script to deal with the Windows update files being present before the script is ran, perhaps by just deleting AppraiserRes.dll and appraiser.sdb if they are present. This way it will work for anyone who attempted to update prior to running the script and then afterwards it will maintain the system's ability to dynamic update.

Great work by the way, this is exactly what I have been looking for as I don't own a single machine that would be officially supported by Windows 11.

**Comment by AveYo** [comment]
That folder is eventually gonna get cleared up by windows after couple of failed attempts.   
It's a good suggestion, but just for the install/remove script, not the part actually doing the bypass.
Thank you for your contribution!
