### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by michelle1574** [AveYo/MediaCreationTool.bat#52]
Please add feature that will download and compile Windows 11 22h2 (dev)

**Comment by AveYo** [comment]
It does not come as an esd that MCT could use, it's insider iso download or uup convert only.

You can however start from a stable release build, then enroll to receive insider builds. 
Readme has a section on how to achieve that for "unsupported" hardware.

I would not recommend to run that on real machines, as it is constantly changed, features come and go, it often breaks, plus it is time-bombed - if you don't keep it updated it will expire leaving you with a non-working windows.
