### ISSUE TITLE
ARM64 ISO Creating Possibility Adding

### ISSUE THREAD

**Issue by OverloadedTech** [AveYo/MediaCreationTool.bat#54]
Hi, please add the feature to download and create a Windows 11 ISO based for ARM64 devices

**Comment by AveYo** [comment]
MediaCreationTool does not support arm64 natively.
It would have to be a script all the way, not via the familiar MCT GUI, and possibly bundling external tools.
Plus I don't have access to an arm64 device to test, and doing it via vm is quite painful. 
So the answer is likely not at this time.

**Comment by OverloadedTech** [comment]
@AveYo No problem

**Comment by Donone19** [comment]
Damn understood bro.
