### ISSUE TITLE
cannot open the  MediaCreationTool.bat

### ISSUE THREAD

**Issue by Laptor1111** [AveYo/MediaCreationTool.bat#56]
I have some problem in running this bat.

**Comment by Laptor1111** [comment]
I can open it through the application (Bracket)

**Comment by Laptor1111** [comment]
what should I do?

**Comment by Laptor1111** [comment]
my file can be opened only through (Bracket)

**Comment by Laptor1111** [comment]
I apologize in advance for my English

**Comment by AveYo** [comment]
if you have some technical details please do provide them, else I cannot do anything about it
