### ISSUE TITLE
Windows Server installation has failed

### ISSUE THREAD

**Issue by EnricoM99** [AveYo/MediaCreationTool.bat#59]
After it has been loading at the blue screen for a while it gets to 81% and then prompts that the computer will restart and then I get this window
![Capture](https://user-images.githubusercontent.com/95731707/145143509-a117b4d7-c3f1-4839-9d68-20c5986c7dfa.PNG)
.

**Comment by EnricoM99** [comment]
Here's what SetupDiag.exe says:

_Error: SetupDiag reports abrupt down-level failure.
Last Operation: Finalize
Error: 0xC1900101 - 0x50016
LogEntry: 2021-12-08 04:23:00, Error                 MOUPG  CDlpActionFinalize::ExecuteSetupPlatformFinalize(1192): Result = 0xC1900101[gle=0x8007000d]_

**Comment by EnricoM99** [comment]
The issue was most likely unrelated since apparently the cause was a double entry for one of the profiles in the registry, so if anyone else is having this same error check profile list in regedit.

**Comment by AveYo** [comment]
Indeed, it is unrelated to the bypass.
Thanks for the quick self-resolve and letting others know about it
