### ISSUE TITLE
Feature Request: Download ISOs for both architectures

### ISSUE THREAD

**Issue by seagull** [AveYo/MediaCreationTool.bat#61]
Hi, the MCT lets you say "both" to the question of x64 or x86 arch, but it isn't clear whether the tool allows this as an option. Does the line
`::# uncomment and change autodetected MediaArch - or rename script:  "x64 iso 1909 Education MediaCreationTool.bat"`
`rem set ARCH=x64`
Provide an option for "both" (or "all" or something) or are the only accepted options x64 and x86; if the latter, can support for "both" be added?
Thanks

**Comment by AveYo** [comment]
I actually anticipated this question. If you go further in the script, at line 89: 
``` bat
::# parse ARCH from script name or commandline - no, it does not accept "both"
for %%s in (%~n0 %*) do for %%A in (x86 x64) do if /i %%s equ %%A set "ARCH=%%A"
```  

Dual-architecture iso is not supported via command line arguments and automation-driven `Create ISO` preset  

But you can select it in the `Select`  preset (or `MCT Defaults` one)

**Comment by seagull** [comment]
Thanks AveYo!
I ended up running the tool once and selecting what version I wanted, then closing it, and launching the tool manually using the `MediaCreationToolXXXX.exe /selfhost` flag. From there I was able to reconfigure things the way I needed them and get an ISO using the right parameters.
