### ISSUE TITLE
what do you want me to do with that? I'm in short supply on crystal balls these days..

### ISSUE THREAD

**Issue by Human19788** [AveYo/MediaCreationTool.bat#64]
what do you want me to do with that? I'm in short supply of crystal balls these days..    
get a qr scan app for your phone and scan it, it will direct you to a microsoft support link  
because if that's an windows setup error - it has nothing to do with this script, your problem is elsewhere  
I can only blindly suggest you run a in-place repair with your current windows 10 version

__Originally posted by @AveYo in https://github.com/AveYo/MediaCreationTool.bat/issues/62#issuecomment-997412047__

__Originally posted by @Human19788 in https://github.com/AveYo/MediaCreationTool.bat/issues/63__active my email address human.hoseini11@outlook.com

**Comment by AveYo** [comment]
hmm, is this a bot? anyway, blocked since he's not conversating
