### ISSUE TITLE
Windows 11 selection is upgrading to Windows Server

### ISSUE THREAD

**Issue by metayyab** [AveYo/MediaCreationTool.bat#65]
Upon selecting Windows 11, it downloads it but while upgrading it shows Windows Server. What is this?

**Comment by metayyab** [comment]
In the first two screenshots, the Setup window is downloading and setting up Windows 11 but in the third screenshot the name of the Setup windows in Titlebar changed to Windows Server and in the last screenshot, it finally starts upgrading to Windows Server.

![2021-12-21 20_06_42-Windows 11 Setup](https://user-images.githubusercontent.com/22665102/146975910-615a642a-45ed-4156-aade-c007b94ba0fb.jpg)
![2021-12-21 20_43_56-](https://user-images.githubusercontent.com/22665102/146975916-412e6f65-ebf2-47af-be02-ca6a286e8dfa.jpg)
![2021-12-21 20_47_40-Windows Server Setup](https://user-images.githubusercontent.com/22665102/146975920-c664c435-3b19-4fa4-98d5-92a6cc9a076a.jpg)

![2021-12-21 20_48_56-Greenshot](https://user-images.githubusercontent.com/22665102/146975925-a9991bd4-c127-41a4-a32c-fde7d0cd9ee1.jpg)

**Comment by AveYo** [comment]
It would have taken you less time to just see the readme and changelog   

First, if you don't need the TPM/SecureBoot/RAM/Storage bypass, use the **MCT Defaults** preset, create a usb / iso media then run setup.exe from that media.

Could also rename script as `def MediaCreationTool.bat` to always create vanilla, no-bypass MCT media no matter the preset.

All other presets include such bypass. It's not easy to please both crowds - and there were far more requests to include the bypass on the most used presets.

As for the why,
>For a more reliable and future-proof experience,
clean installation is still handled via winsetup.dll patching in boot.wim
upgrade is now handled only via auto.cmd with the /Product Server trick
Just ignore the Windows Server label, please!  

It's the most reliable bypass, and it should make no difference if your system is 11-compatible or not. 
Server label is just a label, ignore it, what gets installed anyway is 11

**Comment by AveYo** [comment]
@metayyab,
On second thought I guess for someone with supported hardware it is not ideal to have the bypass applied anyway even if it does not hurt.  Specially when you want to Auto Upgrade, atm it adds the launch options anyway so I will fix that today.

**Comment by metayyab** [comment]
> It would have taken you less time to just see the readme and changelog
> 
> First, if you don't need the TPM/SecureBoot/RAM/Storage bypass, use the **MCT Defaults** preset, create a usb / iso media then run setup.exe from that media.
> 
> Could also rename script as `def MediaCreationTool.bat` to always create vanilla, no-bypass MCT media no matter the preset.
> 
> All other presets include such bypass. It's not easy to please both crowds - and there were far more requests to include the bypass on the most used presets.
> 
> As for the why,
> 
> > For a more reliable and future-proof experience,
> > clean installation is still handled via winsetup.dll patching in boot.wim
> > upgrade is now handled only via auto.cmd with the /Product Server trick
> > Just ignore the Windows Server label, please!
> 
> It's the most reliable bypass, and it should make no difference if your system is 11-compatible or not. Server label is just a label, ignore it, what gets installed anyway is 11
