### ISSUE TITLE
Cannot update Windows 11 through official update (non-insider)

### ISSUE THREAD

**Issue by itFWC** [AveYo/MediaCreationTool.bat#67]
I ran the latest version of the v7 Skip_TPM_Check_on_Dynamic_Update.cmd script, but I am unable to install Windows 11 through the non-insider Windows update.

I checked Regedit, and the keys in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SetupHost.exe` are there.

According to the PC Health Check, the two incompatibilities are that my TPM is on version 1.2 and my CPU is unsupported: it's an Intel Core i5-3470 CPU.

![Screenshot 2021-12-27 014343](https://user-images.githubusercontent.com/96715618/147442845-95564962-74c6-4c68-a6ce-6a771ace43c8.png)

**Comment by AveYo** [comment]
obviously!
you've skipped half the process..

just follow the instructions
`Skip_TPM_Check_on_Dynamic_Update.cmd` disables the setup checks just fine  
but to reach that point via Windows Update on unsupported machines such as yours,
need to use the linked OfflineInsiderEnroll script (or other alternative)

**Comment by itFWC** [comment]
Interesting!

It seems like the Windows 11 update came out for people who aren't part of the Insider Program recently - On a newer laptop, I was able to upgrade to Windows 11 as a regular update, without subscribing to the Windows Insider Program... (This is new, it wasn't even available yesterday on that laptop). I'll try subscribing to the Insider Program!

**Comment by itFWC** [comment]
I enabled telemetry, ran the script, and rebooted my computer. It still doesn't work!

**Comment by AveYo** [comment]
Yes, 11 gets offered as a normal update for supported devices   
and sometimes to ones allegedly unsupported, tho passing all requirements except cpu series  
most definitely won't happen with an ancient i5-3470, 
there was no base for you to put your hopes up and then create this issue ;)

**Comment by itFWC** [comment]
Hmm... There are some websites that link to this repository, suggesting that running the script would suddenly enable Windows 11 to be installed through a Windows update. Clearly, those instructions are misleading.

Obviously, this script was not designed for enabling the upgrade through a normal update; enabling the Windows Insider program is necessary.

Will this script allow Windows 11 to be upgraded through a normal update in the future? Or is that not planned at all?

**Comment by itFWC** [comment]
The i5-3470 is a quad-core processor with a clock speed of 3.20 GHz. Not the fastest CPU in the world, but certainly not sluggish by any means. Windows 11 has been installed successfully on computers with weaker CPUs without any issues.

**Comment by AveYo** [comment]
well, checking this repository's readme is basic courtesy ;)
there's a dedicated section suggestively named ***Get RP/BETA/DEV 11 via Windows Update on "unsupported" hardware***  

as for the cpu, while it works just fine, can't deny it's 9 (nine) generations old
oldest I've got 11 to is a T5500, first mobile series to feature x64 from intel ;)

**Comment by itFWC** [comment]
Yes, I read it, but I had hoped that it would work on normal updates. Updating to Windows 11 through normal updates had just came out and I _assumed_ that the README was simply out of date and that the script would work just as well for normal updates. After all, this is all done through Windows Update regardless.

Anyway, since the upgrade will be installed after I restart the PC, I'm assuming it works fine. I'll reopen if there are any issues with upgrading after the PC reboots (which probably won't happen).
