### ISSUE TITLE
Feature request: Addition of LTSC ISOs to the tool

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [AveYo/MediaCreationTool.bat#70]
As the title says, it would be nice to have access to the LTSC versions of the Windows ISOs.
This could be added as a separate argument the user can edit in the MediaCreationTool.bat.

Since not all Windows versions come with an LTSC counterpart, maybe it would be wise to add a "**(LTSC available)**" note to those who do.

Also, if the user sets the `set LTSC = True` tag, it should be verified only if the `set MCT=XXXX` tag is that of a supported version:
-  `set LTSC = True` and `set MCT=21H2` is a valid option
-  `set LTSC = True` and `set MCT=20H1` isn't a valid option

Forgive me if this is already a feature, or something that can't be implemented.

**Comment by AveYo** [comment]
Script options are not an issue.  
Availability is.  
LTSC is not available officially from microsoft as an electronic software download (ESD)

**Comment by Lovecrafts-Cat** [comment]
Alright, thanks for clearing that up.

If you would like to try some trusted sources, [these are available](https://isofiles.bd581e55.workers.dev/).
The ISOs in that repo were all obtained through My Visual Studio, an online program offered by Microsoft.
The repo is also suggested in the [Friendly Windows Thread guide](https://rentry.org/fwt#links).

If you do not trust these sources, feel free to close this issue.
PS: Thank you for making this tool, it surely helped me and many others.

**Comment by AveYo** [comment]
I am aware of alternate iso sources (provided by fellow MDL members that I fully trust) 
but that's not a legal source. It's just hosted in Russia so Microsoft fails taking them down. 
As you might have probably noticed, those links don't have a reliable uptime or consistent speed.  
Plus, at any time the server operator could alter them and add malware for example - that's the risk with non-microsoft hosted sensitive files such as the OS itself.
Always check downloaded files hashes and don't trust the ones the site itself lists, but verify it matches with publicly known ones (google the hash).

In any case, that's a pre-made iso, not an esd source, you don't need a script for it.
What could be done in the future is a script to generate a LTSC image from a regular esd.
