### ISSUE TITLE
From an ESD or Iso file without TMP

### ISSUE THREAD

**Issue by Plexxor** [AveYo/MediaCreationTool.bat#71]
I wonder because I don't understand the manual how to use your script to make an original Microsoft 22000.318.211104-1236.co_release_svc_refresh_CLIENTBUSINESS_VOL_x64FRE_nl-nl ESD file without TMP?

My regards

**Comment by AveYo** [comment]
I don't understand your request either.  
Do you already have that esd file?
Are you asking how to use `Quick_11_iso_esd_wim_TPM_toggle.bat` on it?
If that's the case:
- run the script once, it will add an entry to the `Send to` menu
- go to the esd file you have via file explorer, right-click it, Send to, `Quick_11_iso_esd_wim_TPM_toggle.bat`
- script will show the image xml on screen and `:D TPM patch added`
- if you repeat the steps, script will undo the changes

**Comment by Plexxor** [comment]
Thank you very much for the info you gave me, and this way I manage to
patch the ESD file.

Best regards and Happy New Year

Op do 30 dec. 2021 om 22:08 schreef AveYo ***@***.***>:
