### ISSUE TITLE
Failed when restarting the computer

### ISSUE THREAD

**Issue by langonginc** [AveYo/MediaCreationTool.bat#82]
I tried to install "Windows 11 Insider Preview 22526.1000 (rs_prerelease)" and I enabled `Skip_TPM_Check_on_Dynamic_Update.cmd`.  But  when I restarted my computer for completing update, there was no any change on my system (I still on 22523).

It restarted and no any info like "Updating".

My System Info:
- Now system version: `22523.1000`
- Expect version: `22526.1000`
- Running latest MediaCreationTool.bat
- Updating requested by "Settings App"

**Comment by AveYo** [comment]
zip and attach your setup log folder from `C:\$WINDOWS.~BT\Sources\Panther\`
_(must enable show hidden files in explorer to see it)_

**Comment by langonginc** [comment]
Oh, I updated successfully by copy `appraiserres.dll` (from windows 10) to `C:\$WINDOWS.~BT\Sources\`.

So I may not be able to provide Panther folder now. Thanks for your help!

But I still don't know why I need to copy this file by myself. Thanks for your help!

**Comment by AveYo** [comment]
the script uses command line switches automatically, not replacing any files  
the logs were needed to figure out why does it not work for you, as it does for many people

**Comment by langonginc** [comment]
Can I give you my data as soon as the next build is published?

**Comment by AveYo** [comment]
only if it does not work ;)

**Comment by langonginc** [comment]
Of course. And there are also errors in the previous versions with me... 🙅

**Comment by langonginc** [comment]
Thanks for your help!

**Comment by langonginc** [comment]
[Panther.zip](https://github.com/AveYo/MediaCreationTool.bat/files/7876226/Panther.zip)

Today, I tried to install 22523.1001, and I failed. Thanks!

**Comment by AveYo** [comment]
@langonginc 
> [Panther.zip](https://github.com/AveYo/MediaCreationTool.bat/files/7876226/Panther.zip)
> 
> Today, I tried to install 22533.1001, and I failed. Thanks!

**The bypass worked flawlessly**
Your issue is unrelated to the TPM requirements

> CompatData_2022_01_16_09_32_42_3_006f0018.xml
> LcsZg1cFoEKfeawY.6.0.0.2.167.6.8.0.0_APPRAISER_EverythingAppInteresting.bin

Setup finds unsupported VirtualBox version 6.18
Update VirtualBox to the latest 6.30 and try again
It's the sensible thing to do when running insider builds..

**Comment by langonginc** [comment]
@AveYo Thank you. 

But, I'm not running windows in VirtualBox
