### ISSUE TITLE
No Enteprise option in Windows 10 1507 MCT

### ISSUE THREAD

**Issue by nguyenthienminh** [AveYo/MediaCreationTool.bat#94]
The option to create a Enterprise\Pro VL\Education VL iso with both x86 and x64 versions isn't in the 1507 Media Creation Tool, whilst it's in the other versions (like 1809 and 21H2). Yes, I do start the MCT from the universal MCT wrapper. Is the option supposed to be there or not?

**Comment by AveYo** [comment]
If you can provide a microsoft link to the 1507 Enterprise esd I will gladly add it..  

Best I could do is add Education (that one was also not supported in original MCT for 1507).
From there you can change product key to Enterprise.

**Comment by nguyenthienminh** [comment]
The thing was, I don't really activate Windows 10 Enterprise thru a product key...
I usually just skip the key prompt and activate thru a remote KMS server later.

**Comment by AveYo** [comment]
There is none. At least publicly shared by microsoft.

**Comment by nguyenthienminh** [comment]
Well, I found some ISO links on the internet leading to the Enterprise **ISO** for 1507, maybe we could extract the wim (or esd) out of the ISO?
32-bit: https://drive.google.com/file/d/1-C3f8uAJZakMldlDE1LnG26x7lt0OXRl/view
64-bit: https://drive.google.com/file/d/1-FnEQfTCepLJe75pniGW4XXaie5uMh-8/view
(I don't know if they're legit or not, plus the drive files are not from me)
