### ISSUE TITLE
Quick tpm toggle

### ISSUE THREAD

**Issue by PaulNevada** [AveYo/MediaCreationTool.bat#96]
Is there any way to uninstall/detach the tool from the SendTo?

**Comment by PaulNevada** [comment]
Found the closed issue. Would be greaat to see it as an option!

**Comment by AveYo** [comment]
I could add a feature to the script so that it removes it if you run it again without arguments.

**Comment by PaulNevada** [comment]
Yes, it'd be just great! Thank you for the great tool and for your time now!

**Comment by AveYo** [comment]
@PaulNevada I have finally implemented the feature you have requested. Thank you!

**Comment by PaulNevada** [comment]
@AveYo Thank you very much!
